#!/usr/bin/env python3

# !!!
# WARNING: This file is autogenerated
# Only modify code within MANUAL() sections
# or your changes may be overwritten later!
# !!!


from __future__ import annotations

from typing import List

import pydantic


class GetAllowedSMSCountryCodesResponse(pydantic.BaseModel):
    """Response type for `CountryCodeAllowlist.get_allowed_sms_country_codes`.
    Fields:
      - request_id: RequestID is a unique identifier to help with debugging the request.
      - country_codes: A list of country codes that are allowed for SMS.
      - status_code: StatusCode is the HTTP status code for the response.
    """  # noqa

    request_id: str
    country_codes: List[str]
    status_code: int


class GetAllowedWhatsAppCountryCodesResponse(pydantic.BaseModel):
    """Response type for `CountryCodeAllowlist.get_allowed_whatsapp_country_codes`.
    Fields:
      - request_id: RequestID is a unique identifier to help with debugging the request.
      - country_codes: A list of country codes that are allowed for WhatsApp.
      - status_code: StatusCode is the HTTP status code for the response.
    """  # noqa

    request_id: str
    country_codes: List[str]
    status_code: int


class SetAllowedSMSCountryCodesResponse(pydantic.BaseModel):
    """Response type for `CountryCodeAllowlist.set_allowed_sms_country_codes`.
    Fields:
      - request_id: RequestID is a unique identifier to help with debugging the request.
      - country_codes: A list of country codes that are allowed for SMS.
      - status_code: StatusCode is the HTTP status code for the response.
    """  # noqa

    request_id: str
    country_codes: List[str]
    status_code: int


class SetAllowedWhatsAppCountryCodesResponse(pydantic.BaseModel):
    """Response type for `CountryCodeAllowlist.set_allowed_whatsapp_country_codes`.
    Fields:
      - request_id: RequestID is a unique identifier to help with debugging the request.
      - country_codes: A list of country codes that are allowed for WhatsApp.
      - status_code: StatusCode is the HTTP status code for the response.
    """  # noqa

    request_id: str
    country_codes: List[str]
    status_code: int
