#!/usr/bin/env python3

# !!!
# WARNING: This file is autogenerated
# Only modify code within MANUAL() sections
# or your changes may be overwritten later!
# !!!


from __future__ import annotations

from enum import Enum
from typing import List, Optional

import pydantic


class FontFamily(str, Enum):
    """FontFamily enum."""

    UNKNOWN_FONT_FAMILY = "UNKNOWN_FONT_FAMILY"
    ARIAL = "ARIAL"
    BRUSH_SCRIPT_MT = "BRUSH_SCRIPT_MT"
    COURIER_NEW = "COURIER_NEW"
    GEORGIA = "GEORGIA"
    HELVETICA = "HELVETICA"
    TAHOMA = "TAHOMA"
    TIMES_NEW_ROMAN = "TIMES_NEW_ROMAN"
    TREBUCHET_MS = "TREBUCHET_MS"
    VERDANA = "VERDANA"


class TemplateType(str, Enum):
    """TemplateType enum."""

    UNKNOWN_TEMPLATE_TYPE = "UNKNOWN_TEMPLATE_TYPE"
    LOGIN = "LOGIN"
    SIGNUP = "SIGNUP"
    INVITE = "INVITE"
    RESET_PASSWORD = "RESET_PASSWORD"
    ONE_TIME_PASSCODE = "ONE_TIME_PASSCODE"
    ONE_TIME_PASSCODE_SIGNUP = "ONE_TIME_PASSCODE_SIGNUP"
    VERIFY_EMAIL_PASSWORD_RESET = "VERIFY_EMAIL_PASSWORD_RESET"
    UNLOCK = "UNLOCK"
    PREBUILT = "PREBUILT"


class TextAlignment(str, Enum):
    """TextAlignment enum."""

    UNKNOWN_TEXT_ALIGNMENT = "UNKNOWN_TEXT_ALIGNMENT"
    LEFT = "LEFT"
    CENTER = "CENTER"


class CustomHTMLCustomization(pydantic.BaseModel):
    """
    Fields:
      - template_type: TemplateType is the type of email template for which this custom HTML customization is valid.
      - html_content: HTMLContent is the HTML content of the email body.
      - plaintext_content: PlaintextContent is the plaintext content of the email body.
      - subject: Subject is the subject line in the email template.
    """  # noqa

    template_type: Optional[TemplateType] = None
    html_content: Optional[str] = None
    plaintext_content: Optional[str] = None
    subject: Optional[str] = None


class PrebuiltCustomization(pydantic.BaseModel):
    """
    Fields:
      - button_border_radius: ButtonBorderRadius is the radius of the button border in the email body.
      - button_color: ButtonColor is the color of the button in the email body.
      - button_text_color: ButtonTextColor is the color of the text in the button in the email body.
      - font_family: FontFamily is the font type to be used in the email body.
      - text_alignment: TextAlignment is the alignment of the text in the email body.
    """  # noqa

    button_border_radius: Optional[float] = None
    button_color: Optional[str] = None
    button_text_color: Optional[str] = None
    font_family: Optional[FontFamily] = None
    text_alignment: Optional[TextAlignment] = None


class SenderInformation(pydantic.BaseModel):
    """
    Fields:
      - from_local_part: FromLocalPart is the prefix of the sender’s email address, everything before the @ symbol (e.g., first.last).
      - from_domain: FromDomain is the postfix of the sender’s email address, everything after the @ symbol (e.g., stytch.com).
      - from_name: FromName is the sender of the email (e.g., Login).
      - reply_to_local_part: ReplyToLocalPart is the prefix of the reply-to email address, everything before the @ symbol (e.g., first.last).
      - reply_to_name: ReplyToName is the sender of the reply-to email address (e.g., Support).
    """  # noqa

    from_local_part: Optional[str] = None
    from_domain: Optional[str] = None
    from_name: Optional[str] = None
    reply_to_local_part: Optional[str] = None
    reply_to_name: Optional[str] = None


class EmailTemplate(pydantic.BaseModel):
    """
    Fields:
      - template_id: TemplateID is a unique identifier to use for the template – this is how you will refer to the template when sending emails from your project or managing this template. It can never be changed after creation.
      - name: Name is a human-readable name. This does not have to be unique.
      - sender_information: SenderInformation is information about the email sender, such as the reply address or rendered name. This is an optional field for PrebuiltCustomization, but required for CustomHTMLCustomization.
      - prebuilt_customization: PrebuiltCustomization is customization related to prebuilt fields (such as button color) for prebuilt email templates.
      - custom_html_customization: CustomHTMLCustomization is customization defined for completely custom HTML email templates.
    """  # noqa

    template_id: str
    name: Optional[str] = None
    sender_information: Optional[SenderInformation] = None
    prebuilt_customization: Optional[PrebuiltCustomization] = None
    custom_html_customization: Optional[CustomHTMLCustomization] = None


class CreateResponse(pydantic.BaseModel):
    """Response type for `EmailTemplates.create`.
    Fields:
      - request_id: RequestID is a unique identifier to help with debugging the request.
      - email_template: EmailTemplate is the email template that was created.
      - status_code: StatusCode is the HTTP status code for the response.
    """  # noqa

    request_id: str
    email_template: EmailTemplate
    status_code: int


class DeleteResponse(pydantic.BaseModel):
    """Response type for `EmailTemplates.delete`.
    Fields:
      - request_id: RequestID is a unique identifier to help with debugging the request.
      - status_code: StatusCode is the HTTP status code for the response.
    """  # noqa

    request_id: str
    status_code: int


class GetAllResponse(pydantic.BaseModel):
    """Response type for `EmailTemplates.get_all`.
    Fields:
      - request_id: RequestID is a unique identifier to help with debugging the request.
      - email_templates: EmailTemplates is a list of all active email templates for the project.
      - status_code: StatusCode is the HTTP status code for the response.
    """  # noqa

    request_id: str
    email_templates: List[EmailTemplate]
    status_code: int


class GetDefaultResponse(pydantic.BaseModel):
    """Response type for `EmailTemplates.get_default`.
    Fields:
      - request_id: RequestID is a unique identifier to help with debugging the request.
      - template_id: TemplateID is a unique identifier to use for the template – this is how you will refer to the template when sending emails from your project or managing this template. It can never be changed after creation.
      - status_code: StatusCode is the HTTP status code for the response.
    """  # noqa

    request_id: str
    template_id: str
    status_code: int


class GetResponse(pydantic.BaseModel):
    """Response type for `EmailTemplates.get`.
    Fields:
      - request_id: RequestID is a unique identifier to help with debugging the request.
      - email_template: EmailTemplate is the email template.
      - status_code: StatusCode is the HTTP status code for the response.
    """  # noqa

    request_id: str
    email_template: EmailTemplate
    status_code: int


class SetDefaultResponse(pydantic.BaseModel):
    """Response type for `EmailTemplates.set_default`.
    Fields:
      - request_id: RequestID is a unique identifier to help with debugging the request.
      - status_code: StatusCode is the HTTP status code for the response.
    """  # noqa

    request_id: str
    status_code: int


class UnsetDefaultResponse(pydantic.BaseModel):
    """Response type for `EmailTemplates.unset_default`.
    Fields:
      - request_id: RequestID is a unique identifier to help with debugging the request.
      - status_code: StatusCode is the HTTP status code for the response.
    """  # noqa

    request_id: str
    status_code: int


class UpdateResponse(pydantic.BaseModel):
    """Response type for `EmailTemplates.update`.
    Fields:
      - request_id: RequestID is a unique identifier to help with debugging the request.
      - email_template: EmailTemplate is the newly updated email template.
      - status_code: StatusCode is the HTTP status code for the response.
    """  # noqa

    request_id: str
    email_template: EmailTemplate
    status_code: int
