#!/usr/bin/env python3

# !!!
# WARNING: This file is autogenerated
# Only modify code within MANUAL() sections
# or your changes may be overwritten later!
# !!!


from __future__ import annotations

from enum import Enum
from typing import List, Optional

import pydantic


class EnvironmentType(str, Enum):
    """EnvironmentType enum."""

    UNKNOWN_ENVIRONMENT_TYPE = "UNKNOWN_ENVIRONMENT_TYPE"
    LIVE = "LIVE"
    TEST = "TEST"


class Environment(pydantic.BaseModel):
    """
    Fields:
      - environment_slug: EnvironmentSlug is the slug of the environment.
      - project_slug: The slug of the project.
      - name: Name is a human-readable name. This does not have to be unique.
      - oauth_callback_id: The callback ID used in OAuth requests for the environment.
      - cross_org_passwords_enabled: CrossOrgPasswordsEnabled indicates whether the environment uses cross-org passwords.
      - user_impersonation_enabled: Indicates whether user impersonation is enabled for the environment.
      - zero_downtime_session_migration_url: ZeroDowntimeSessionMigrationURL is the OIDC-compliant UserInfo endpoint for session migration.
      - use_custom_domain_in_magic_link_emails: (no documentation yet)
      - user_lock_self_serve_enabled: Indicates whether users in the environment who get locked out should automatically get an unlock email magic link.
      - user_lock_threshold: UserLockThreshold represents the number of failed authenticate attempts that will cause a user in the environment to be locked. Defaults to 10.
      - user_lock_ttl: Represents the time in seconds that the user in the environment remains locked once the lock is set. Defaults to 1 hour (3600 seconds).
      - idp_authorization_url: The OpenID Configuration endpoint for Connected Apps for the environment.
      - idp_dynamic_client_registration_enabled: IDPDynamicClientRegistrationEnabled indicates whether the project has opted in to Dynamic Client Registration (DCR) for Connected Apps.
      - idp_dynamic_client_registration_access_token_template_content: IDPDynamicClientRegistrationAccessTokenTemplateContent is the access token template to use for clients created through Dynamic Client Registration (DCR).
      - project_id: (no documentation yet)
      - type: The environment's type.
      - created_at: The ISO-8601 timestamp for when the resource was created.
    """  # noqa

    environment_slug: str
    project_slug: str
    name: str
    oauth_callback_id: str
    cross_org_passwords_enabled: bool
    user_impersonation_enabled: bool
    zero_downtime_session_migration_url: str
    use_custom_domain_in_magic_link_emails: bool
    user_lock_self_serve_enabled: bool
    user_lock_threshold: int
    user_lock_ttl: int
    idp_authorization_url: str
    idp_dynamic_client_registration_enabled: bool
    idp_dynamic_client_registration_access_token_template_content: str
    project_id: str
    type: Optional[EnvironmentType] = None
    created_at: Optional[str] = None


class Metrics(pydantic.BaseModel):
    """
    Fields:
      - user_count: The number of active users in the environment (only relevant for Consumer projects).
      - organization_count: OrganizationCount is the number of active organizations in the environment (only relevant for B2B projects).
      - member_count: MemberCount is the number of active members in the environment (only relevant for B2B projects).
      - m2m_client_count: M2MClientCount is the number of active M2M clients in the environment.
    """  # noqa

    user_count: int
    organization_count: int
    member_count: int
    m2m_client_count: int


class CreateResponse(pydantic.BaseModel):
    """Response type for `Environments.create`.
    Fields:
      - request_id: RequestID is a unique identifier to help with debugging the request.
      - environment: Environment contains the details for the newly created environment.
      - status_code: StatusCode is the HTTP status code for the response.
    """  # noqa

    request_id: str
    environment: Environment
    status_code: int


class DeleteResponse(pydantic.BaseModel):
    """Response type for `Environments.delete`.
    Fields:
      - request_id: RequestID is a unique identifier to help with debugging the request.
      - status_code: StatusCode is the HTTP status code for the response.
    """  # noqa

    request_id: str
    status_code: int


class GetAllResponse(pydantic.BaseModel):
    """Response type for `Environments.get_all`.
    Fields:
      - request_id: RequestID is a unique identifier to help with debugging the request.
      - environments: Environments is the list of environments that belong to the specified project.
      - status_code: StatusCode is the HTTP status code for the response.
    """  # noqa

    request_id: str
    environments: List[Environment]
    status_code: int


class GetMetricsResponse(pydantic.BaseModel):
    """Response type for `Environments.get_metrics`.
    Fields:
      - request_id: RequestID is a unique identifier to help with debugging the request.
      - metrics: Metrics contains various metrics for the environment.
      - status_code: StatusCode is the HTTP status code for the response.
    """  # noqa

    request_id: str
    metrics: Metrics
    status_code: int


class GetResponse(pydantic.BaseModel):
    """Response type for `Environments.get`.
    Fields:
      - request_id: RequestID is a unique identifier to help with debugging the request.
      - environment: Environment contains the environment details.
      - status_code: StatusCode is the HTTP status code for the response.
    """  # noqa

    request_id: str
    environment: Environment
    status_code: int


class UpdateResponse(pydantic.BaseModel):
    """Response type for `Environments.update`.
    Fields:
      - request_id: RequestID is a unique identifier to help with debugging the request.
      - environment: Environment contains the details for the updated environment.
      - status_code: StatusCode is the HTTP status code for the response.
    """  # noqa

    request_id: str
    environment: Environment
    status_code: int
