#!/usr/bin/env python3

# !!!
# WARNING: This file is autogenerated
# Only modify code within MANUAL() sections
# or your changes may be overwritten later!
# !!!


from __future__ import annotations

from enum import Enum
from typing import Optional

import pydantic


class DatadogSite(str, Enum):
    """DatadogSite enum."""

    DATADOG_SITE_UNSPECIFIED = "DATADOG_SITE_UNSPECIFIED"
    US = "US"
    US3 = "US3"
    US5 = "US5"
    EU = "EU"
    AP1 = "AP1"


class DestinationType(str, Enum):
    """DestinationType enum."""

    DESTINATION_TYPE_UNSPECIFIED = "DESTINATION_TYPE_UNSPECIFIED"
    DATADOG = "DATADOG"
    GRAFANA_LOKI = "GRAFANA_LOKI"


class StreamingStatus(str, Enum):
    """StreamingStatus enum."""

    STREAMING_STATUS_UNSPECIFIED = "STREAMING_STATUS_UNSPECIFIED"
    ACTIVE = "ACTIVE"
    DISABLED = "DISABLED"
    PENDING = "PENDING"


class DatadogConfig(pydantic.BaseModel):
    """
    Fields:
      - api_key: APIKey is the API key for submitting logs to a Datadog account.
      - site: Site is one of the supported DatadogSite constants.
    """  # noqa

    api_key: str
    site: Optional[DatadogSite] = None


class DatadogConfigMasked(pydantic.BaseModel):
    """
    Fields:
      - api_key_last_four: APIKeyLastFour is the last four characters of the API key in use.
      - site: Site is one of the supported DatadogSite constants.
    """  # noqa

    api_key_last_four: str
    site: Optional[DatadogSite] = None


class GrafanaLokiConfig(pydantic.BaseModel):
    """
    Fields:
      - hostname: Hostname is the hostname of the Grafana Loki instance to which to send events.
      - username: Username is the username for authenticating the request to a Grafana Loki instance.
      - password: Password is the password for authenticating the request to a Grafana Loki instance.
    """  # noqa

    hostname: str
    username: str
    password: str


class DestinationConfig(pydantic.BaseModel):
    """
    Fields:
      - datadog: Datadog configuration settings for the destination.
      - grafana_loki: Grafana Loki configuration settings for the destination.
    """  # noqa

    datadog: Optional[DatadogConfig] = None
    grafana_loki: Optional[GrafanaLokiConfig] = None


class EventLogStreaming(pydantic.BaseModel):
    """
    Fields:
      - destination_type: DestinationType is the type of destination to which to send events.
      - destination_config: DestinationConfig is the configuration for the destination to which to send events.
      - streaming_status: Indicates whether event log streaming is enabled or disabled for the environment.
    """  # noqa

    destination_type: Optional[DestinationType] = None
    destination_config: Optional[DestinationConfig] = None
    streaming_status: Optional[StreamingStatus] = None


class GrafanaLokiConfigMasked(pydantic.BaseModel):
    """
    Fields:
      - hostname: Hostname is the hostname of the Grafana Loki instance to which to send events.
      - username: Username is the username for authenticating the request to a Grafana Loki instance.
      - password_last_four: PasswordLastFour is the last four characters of the password in use.
    """  # noqa

    hostname: str
    username: str
    password_last_four: str


class DestinationConfigMasked(pydantic.BaseModel):
    """
    Fields:
      - datadog: Datadog configuration settings for the destination.
      - grafana_loki: Grafana Loki configuration settings for the destination.
    """  # noqa

    datadog: Optional[DatadogConfigMasked] = None
    grafana_loki: Optional[GrafanaLokiConfigMasked] = None


class EventLogStreamingMasked(pydantic.BaseModel):
    """
    Fields:
      - destination_type: DestinationType is the type of destination to which to send events.
      - destination_config: DestinationConfig is the configuration for the destination to which to send events.
      - streaming_status: Indicates whether event log streaming is enabled or disabled for the environment.
    """  # noqa

    destination_type: Optional[DestinationType] = None
    destination_config: Optional[DestinationConfigMasked] = None
    streaming_status: Optional[StreamingStatus] = None


class CreateResponse(pydantic.BaseModel):
    """Response type for `EventLogStreaming.create`.
    Fields:
      - request_id: RequestID is a unique identifier to help with debugging the request.
      - event_log_streaming_config: EventLogStreamingConfig is the configuration that was created.
      - status_code: StatusCode is the HTTP status code for the response.
    """  # noqa

    request_id: str
    event_log_streaming_config: EventLogStreaming
    status_code: int


class DeleteResponse(pydantic.BaseModel):
    """Response type for `EventLogStreaming.delete`.
    Fields:
      - request_id: RequestID is a unique identifier to help with debugging the request.
      - status_code: StatusCode is the HTTP status code for the response.
    """  # noqa

    request_id: str
    status_code: int


class DisableResponse(pydantic.BaseModel):
    """Response type for `EventLogStreaming.disable`.
    Fields:
      - request_id: RequestID is a unique identifier to help with debugging the request.
      - status_code: StatusCode is the HTTP status code for the response.
    """  # noqa

    request_id: str
    status_code: int


class EnableResponse(pydantic.BaseModel):
    """Response type for `EventLogStreaming.enable`.
    Fields:
      - request_id: RequestID is a unique identifier to help with debugging the request.
      - status_code: StatusCode is the HTTP status code for the response.
    """  # noqa

    request_id: str
    status_code: int


class GetResponse(pydantic.BaseModel):
    """Response type for `EventLogStreaming.get`.
    Fields:
      - request_id: RequestID is a unique identifier to help with debugging the request.
      - event_log_streaming_config: EventLogStreamingConfig is the event log streaming configuration, with sensitive values masked (e.g., APIKey, Password).
      - status_code: StatusCode is the HTTP status code for the response.
    """  # noqa

    request_id: str
    event_log_streaming_config: EventLogStreamingMasked
    status_code: int


class UpdateResponse(pydantic.BaseModel):
    """Response type for `EventLogStreaming.update`.
    Fields:
      - request_id: RequestID is a unique identifier to help with debugging the request.
      - event_log_streaming_config: EventLogStreamingConfig is the configuration that was updated.
      - status_code: StatusCode is the HTTP status code for the response.
    """  # noqa

    request_id: str
    event_log_streaming_config: EventLogStreaming
    status_code: int
