#!/usr/bin/env python3

# !!!
# WARNING: This file is autogenerated
# Only modify code within MANUAL() sections
# or your changes may be overwritten later!
# !!!


from __future__ import annotations

from enum import Enum
from typing import Optional

import pydantic


class JWTTemplateType(str, Enum):
    """JWTTemplateType enum."""

    UNKNOWN_TEMPLATE_TYPE = "UNKNOWN_TEMPLATE_TYPE"
    SESSION = "SESSION"
    M2M = "M2M"


class JWTTemplate(pydantic.BaseModel):
    """
    Fields:
      - template_content: TemplateContent is the JWT template content.
      - custom_audience: CustomAudience is an optional custom audience for the JWT template.
      - jwt_template_type: JWTTemplateType is the type of JWT template.
    """  # noqa

    template_content: str
    custom_audience: str
    jwt_template_type: Optional[JWTTemplateType] = None


class GetResponse(pydantic.BaseModel):
    """Response type for `JWTTemplates.get`.
    Fields:
      - request_id: RequestID is a unique identifier to help with debugging the request.
      - jwt_template: JWTTemplate is the JWT template for the requested JWTTemplateType.
      - status_code: StatusCode is the HTTP status code for the response.
    """  # noqa

    request_id: str
    jwt_template: JWTTemplate
    status_code: int


class SetResponse(pydantic.BaseModel):
    """Response type for `JWTTemplates.set`.
    Fields:
      - request_id: RequestID is a unique identifier to help with debugging the request.
      - jwt_template: JWTTemplate is the JWT template for the requested JWTTemplateType.
      - status_code: StatusCode is the HTTP status code for the response.
    """  # noqa

    request_id: str
    jwt_template: JWTTemplate
    status_code: int
