#!/usr/bin/env python3

# !!!
# WARNING: This file is autogenerated
# Only modify code within MANUAL() sections
# or your changes may be overwritten later!
# !!!


from __future__ import annotations

from enum import Enum
from typing import Optional

import pydantic


class ValidationPolicy(str, Enum):
    """ValidationPolicy enum."""

    UNKNOWN_VALIDATION_POLICY = "UNKNOWN_VALIDATION_POLICY"
    ZXCVBN = "ZXCVBN"
    LUDS = "LUDS"


class PasswordStrengthConfig(pydantic.BaseModel):
    """
    Fields:
      - check_breach_on_creation: CheckBreachOnCreation is a flag to check whether to use the HaveIBeenPwned database to detect password breaches when a user first creates their password.
      - check_breach_on_authentication: CheckBreachOnAuthentication denotes whether to use the HaveIBeenPwned database to detect password breaches when a user authenticates.
      - validate_on_authentication: ValidateOnAuthentication notes whether to require a password reset on authentication if a user's current password no longer meets the project's current policy requirements.
      - validation_policy: ValidationPolicy is the policy to use for password validation.
      - luds_min_password_length: LudsMinPasswordLength is the minimum number of characters in a password if using a LUDS validation_policy. This field is nil when using the ZXCVBN validation_policy.
      - luds_min_password_complexity: LudsMinPasswordComplexity is the minimum number of "character types" in a password (Lowercase, Uppercase, Digits, Symbols) when using a LUDS validation_policy. This field is nil when using the ZXCVBN validation_policy.
    """  # noqa

    check_breach_on_creation: bool
    check_breach_on_authentication: bool
    validate_on_authentication: bool
    validation_policy: Optional[ValidationPolicy] = None
    luds_min_password_length: Optional[int] = None
    luds_min_password_complexity: Optional[int] = None


class GetResponse(pydantic.BaseModel):
    """Response type for `PasswordStrengthConfig.get`.
    Fields:
      - request_id: RequestID is a unique identifier to help with debugging the request.
      - password_strength_config: PasswordStrengthConfig is the password strength configuration for the environment.
      - status_code: StatusCode is the HTTP status code for the response.
    """  # noqa

    request_id: str
    password_strength_config: PasswordStrengthConfig
    status_code: int


class SetResponse(pydantic.BaseModel):
    """Response type for `PasswordStrengthConfig.set`.
    Fields:
      - request_id: RequestID is a unique identifier to help with debugging the request.
      - password_strength_config: PasswordStrengthConfig is the password strength configuration for the environment.
      - status_code: StatusCode is the HTTP status code for the response.
    """  # noqa

    request_id: str
    password_strength_config: PasswordStrengthConfig
    status_code: int
