#!/usr/bin/env python3

# !!!
# WARNING: This file is autogenerated
# Only modify code within MANUAL() sections
# or your changes may be overwritten later!
# !!!


from __future__ import annotations

from enum import Enum
from typing import List, Optional

import pydantic


class Vertical(str, Enum):
    """Vertical enum."""

    UNKNOWN = "UNKNOWN"
    ALL = "ALL"
    CONSUMER = "CONSUMER"
    B2B = "B2B"


class Project(pydantic.BaseModel):
    """
    Fields:
      - project_slug: The slug of the project.
      - name: Name is a human-readable name. This does not have to be unique.
      - vertical: Vertical is the project's vertical.
      - created_at: The ISO-8601 timestamp for when the resource was created.
    """  # noqa

    project_slug: str
    name: str
    vertical: Optional[Vertical] = None
    created_at: Optional[str] = None


class CreateResponse(pydantic.BaseModel):
    """Response type for `Projects.create`.
    Fields:
      - request_id: RequestID is a unique identifier to help with debugging the request.
      - project: Project contains the details for the newly created project.
      - status_code: StatusCode is the HTTP status code for the response.
    """  # noqa

    request_id: str
    project: Project
    status_code: int


class DeleteResponse(pydantic.BaseModel):
    """Response type for `Projects.delete`.
    Fields:
      - request_id: RequestID is a unique identifier to help with debugging the request.
      - status_code: StatusCode is the HTTP status code for the response.
    """  # noqa

    request_id: str
    status_code: int


class GetAllResponse(pydantic.BaseModel):
    """Response type for `Projects.get_all`.
    Fields:
      - request_id: RequestID is a unique identifier to help with debugging the request.
      - projects: Projects is a list of all active projects in the workspace.
      - status_code: StatusCode is the HTTP status code for the response.
    """  # noqa

    request_id: str
    projects: List[Project]
    status_code: int


class GetResponse(pydantic.BaseModel):
    """Response type for `Projects.get`.
    Fields:
      - request_id: RequestID is a unique identifier to help with debugging the request.
      - project: Project contains the project details.
      - status_code: StatusCode is the HTTP status code for the response.
    """  # noqa

    request_id: str
    project: Project
    status_code: int


class UpdateResponse(pydantic.BaseModel):
    """Response type for `Projects.update`.
    Fields:
      - request_id: RequestID is a unique identifier to help with debugging the request.
      - project: Project contains the updated project details.
      - status_code: StatusCode is the HTTP status code for the response.
    """  # noqa

    request_id: str
    project: Project
    status_code: int
