#!/usr/bin/env python3

# !!!
# WARNING: This file is autogenerated
# Only modify code within MANUAL() sections
# or your changes may be overwritten later!
# !!!


from __future__ import annotations

from typing import List, Optional

import pydantic


class PublicToken(pydantic.BaseModel):
    """
    Fields:
      - public_token: The public token value as well as the unique identifier for the token.
      - created_at: The ISO-8601 timestamp for when the resource was created.
    """  # noqa

    public_token: str
    created_at: Optional[str] = None


class CreateResponse(pydantic.BaseModel):
    """Response type for `PublicTokens.create`.
    Fields:
      - request_id: RequestID is a unique identifier to help with debugging the request.
      - public_token: Contains details about the public token object.
      - status_code: StatusCode is the HTTP status code for the response.
    """  # noqa

    request_id: str
    public_token: PublicToken
    status_code: int


class DeleteResponse(pydantic.BaseModel):
    """Response type for `PublicTokens.delete`.
    Fields:
      - request_id: RequestID is a unique identifier to help with debugging the request.
      - status_code: StatusCode is the HTTP status code for the response.
    """  # noqa

    request_id: str
    status_code: int


class GetAllResponse(pydantic.BaseModel):
    """Response type for `PublicTokens.get_all`.
    Fields:
      - request_id: RequestID is a unique identifier to help with debugging the request.
      - public_tokens: All the public tokens that belong to the environment.
      - status_code: StatusCode is the HTTP status code for the response.
    """  # noqa

    request_id: str
    public_tokens: List[PublicToken]
    status_code: int


class GetResponse(pydantic.BaseModel):
    """Response type for `PublicTokens.get`.
    Fields:
      - request_id: RequestID is a unique identifier to help with debugging the request.
      - public_token: Contains details about the public token object.
      - status_code: StatusCode is the HTTP status code for the response.
    """  # noqa

    request_id: str
    public_token: PublicToken
    status_code: int
