#!/usr/bin/env python3

# !!!
# WARNING: This file is autogenerated
# Only modify code within MANUAL() sections
# or your changes may be overwritten later!
# !!!


from __future__ import annotations

from typing import List, Optional

import pydantic


class Permission(pydantic.BaseModel):
    """
    Fields:
      - resource_id: ResourceID is a human-readable name that is unique within the environment.
      - actions: Actions is an array of actions that the role can perform on the given resource.
    """  # noqa

    resource_id: str
    actions: List[str]


class DefaultRole(pydantic.BaseModel):
    """
    Fields:
      - permissions: Permissions are the permissions granted to this role for resources within the environment.
    """  # noqa

    permissions: List[Permission]


class Resource(pydantic.BaseModel):
    """
    Fields:
      - resource_id: ResourceID is a human-readable name that is unique within the environment.
      - description: Description is a description for the role.
      - available_actions: AvailableActions are the actions that can be granted for this resource.
    """  # noqa

    resource_id: str
    description: str
    available_actions: List[str]


class Role(pydantic.BaseModel):
    """
    Fields:
      - role_id: RoleID is a human-readable name that is unique within the environment.
      - description: Description is a description for the role.
      - permissions: Permissions are the permissions granted to this role for resources within the environment.
    """  # noqa

    role_id: str
    description: str
    permissions: List[Permission]


class Scope(pydantic.BaseModel):
    """
    Fields:
      - scope: Scope is a human-readable name that is unique within the environment.
      - description: Description is a description for the role.
      - permissions: Permissions are the permissions granted to this role for resources within the environment.
    """  # noqa

    scope: str
    description: str
    permissions: List[Permission]


class Policy(pydantic.BaseModel):
    """
    Fields:
      - stytch_resources: StytchResources consists of resources created by Stytch that always exist. This field will be returned in relevant Policy objects but can never be overridden or deleted.
      - custom_roles: The following fields are valid for both B2B and Consumer projects: CustomRoles are additional roles that exist within the environment beyond the stytch_member, stytch_admin, or stytch_user roles.
      - custom_resources: CustomResources are resources that exist within the environment beyond those defined within the stytch_resources.
      - custom_scopes: CustomScopes are additional scopes that exist within the environment beyond those defined by default.
      - stytch_member: The following fields are valid for B2B projects only: StytchMember is the default role given to members within the environment. Only permissions are returned; role_id and description are managed by Stytch.
      - stytch_admin: StytchAdmin is the role assigned to admins within an organization. Only permissions are returned; role_id and description are managed by Stytch.
      - stytch_user: The following field is valid for Consumer projects only: StytchUser is the default role given to users within the environment. Only permissions are returned; role_id and description are managed by Stytch.
    """  # noqa

    stytch_resources: List[Resource]
    custom_roles: List[Role]
    custom_resources: List[Resource]
    custom_scopes: List[Scope]
    stytch_member: Optional[DefaultRole] = None
    stytch_admin: Optional[DefaultRole] = None
    stytch_user: Optional[DefaultRole] = None


class GetResponse(pydantic.BaseModel):
    """Response type for `RBACPolicy.get`.
    Fields:
      - request_id: RequestID is a unique identifier to help with debugging the request.
      - policy: Policy is the RBAC policy for the environment.
      - status_code: StatusCode is the HTTP status code for the response.
    """  # noqa

    request_id: str
    policy: Policy
    status_code: int


class SetResponse(pydantic.BaseModel):
    """Response type for `RBACPolicy.set`.
    Fields:
      - request_id: RequestID is a unique identifier to help with debugging the request.
      - policy: Policy is the RBAC policy for the environment.
      - status_code: StatusCode is the HTTP status code for the response.
    """  # noqa

    request_id: str
    policy: Policy
    status_code: int
