#!/usr/bin/env python3

# !!!
# WARNING: This file is autogenerated
# Only modify code within MANUAL() sections
# or your changes may be overwritten later!
# !!!


from __future__ import annotations

from enum import Enum
from typing import List, Optional

import pydantic


class RedirectURLType(str, Enum):
    """RedirectURLType enum."""

    UNKNOWN_REDIRECT_TYPE = "UNKNOWN_REDIRECT_TYPE"
    LOGIN = "LOGIN"
    INVITE = "INVITE"
    SIGNUP = "SIGNUP"
    RESET_PASSWORD = "RESET_PASSWORD"
    DISCOVERY = "DISCOVERY"


class URLType(pydantic.BaseModel):
    """
    Fields:
      - is_default: IsDefault is true if this is the default redirect type, false otherwise.
      - type: One of the RedirectType values.
    """  # noqa

    is_default: bool
    type: Optional[RedirectURLType] = None


class RedirectURL(pydantic.BaseModel):
    """
    Fields:
      - url: The URL to which to redirect.
      - valid_types: ValidTypes is a list of all the URLRedirectType available for this URL.
    """  # noqa

    url: str
    valid_types: List[URLType]


class CreateResponse(pydantic.BaseModel):
    """Response type for `RedirectURLs.create`.
    Fields:
      - request_id: RequestID is a unique identifier to help with debugging the request.
      - redirect_url: RedirectURL is the object that was created.
      - status_code: StatusCode is the HTTP status code for the response.
    """  # noqa

    request_id: str
    redirect_url: RedirectURL
    status_code: int


class DeleteResponse(pydantic.BaseModel):
    """Response type for `RedirectURLs.delete`.
    Fields:
      - request_id: RequestID is a unique identifier to help with debugging the request.
      - status_code: StatusCode is the HTTP status code for the response.
    """  # noqa

    request_id: str
    status_code: int


class GetAllResponse(pydantic.BaseModel):
    """Response type for `RedirectURLs.get_all`.
    Fields:
      - request_id: RequestID is a unique identifier to help with debugging the request.
      - redirect_urls: RedirectURLs is a list of all the redirect URLs for the project.
      - status_code: StatusCode is the HTTP status code for the response.
    """  # noqa

    request_id: str
    redirect_urls: List[RedirectURL]
    status_code: int


class GetResponse(pydantic.BaseModel):
    """Response type for `RedirectURLs.get`.
    Fields:
      - request_id: RequestID is a unique identifier to help with debugging the request.
      - redirect_url: RedirectURL is the redirect URL.
      - status_code: StatusCode is the HTTP status code for the response.
    """  # noqa

    request_id: str
    redirect_url: RedirectURL
    status_code: int


class UpdateResponse(pydantic.BaseModel):
    """Response type for `RedirectURLs.update`.
    Fields:
      - request_id: RequestID is a unique identifier to help with debugging the request.
      - redirect_url: RedirectURL is the object that was updated.
      - status_code: StatusCode is the HTTP status code for the response.
    """  # noqa

    request_id: str
    redirect_url: RedirectURL
    status_code: int
