#!/usr/bin/env python3

# !!!
# WARNING: This file is autogenerated
# Only modify code within MANUAL() sections
# or your changes may be overwritten later!
# !!!


from __future__ import annotations

from enum import Enum
from typing import List, Optional

import pydantic


class B2BCookiesConfigHttpOnly(str, Enum):
    """B2BCookiesConfigHttpOnly enum."""

    DISABLED = "DISABLED"
    ENABLED = "ENABLED"
    ENFORCED = "ENFORCED"


class ConsumerCookiesConfigHttpOnly(str, Enum):
    """ConsumerCookiesConfigHttpOnly enum."""

    DISABLED = "DISABLED"
    ENABLED = "ENABLED"
    ENFORCED = "ENFORCED"


class DFPPAOnChallengeAction(str, Enum):
    """DFPPAOnChallengeAction enum."""

    UNKNOWN_DFPPA_ON_CHALLENGE_ACTION = "UNKNOWN_DFPPA_ON_CHALLENGE_ACTION"
    ALLOW = "ALLOW"
    BLOCK = "BLOCK"
    TRIGGER_CAPTCHA = "TRIGGER_CAPTCHA"


class DFPPASetting(str, Enum):
    """DFPPASetting enum."""

    UNKNOWN_DFPPA_SETTING = "UNKNOWN_DFPPA_SETTING"
    ENABLED = "ENABLED"
    PASSIVE = "PASSIVE"
    DISABLED = "DISABLED"


class SMSAutofillMetadataMetadataType(str, Enum):
    """SMSAutofillMetadataMetadataType enum."""

    DOMAIN = "domain"
    HASH = "hash"


class AuthorizedB2BDomain(pydantic.BaseModel):
    """
    Fields:
      - domain: Domain is the domain name. Stytch uses the same-origin policy to determine matches.
      - slug_pattern: SlugPattern is the slug pattern that can be used to support authentication flows specific to each organization. An example value here might be 'https://{{slug}}.example.com'. The value **must** include '{{slug}}' as a placeholder for the slug.
    """  # noqa

    domain: str
    slug_pattern: str


class B2BBasicConfig(pydantic.BaseModel):
    """
    Fields:
      - enabled: Enabled indicates whether the B2B project SDK is enabled. This allows the SDK to manage user and session data.
      - allow_self_onboarding: AllowSelfOnboarding indicates whether self-onboarding is allowed for members in the SDK.
      - enable_member_permissions: EnableMemberPermissions indicates whether member permissions RBAC are enabled in the SDK.
      - domains: Domains is a list of domains authorized for use in the SDK.
      - bundle_ids: BundleIDs is a list of bundle IDs authorized for use in the SDK.
    """  # noqa

    enabled: bool
    allow_self_onboarding: bool
    enable_member_permissions: bool
    domains: List[AuthorizedB2BDomain]
    bundle_ids: List[str]


class B2BCookiesConfig(pydantic.BaseModel):
    """
    Fields:
      - http_only: Specifies whether cookies should be set with the HttpOnly flag.
    """  # noqa

    http_only: B2BCookiesConfigHttpOnly


class B2BDFPPAConfig(pydantic.BaseModel):
    """
    Fields:
      - enabled: Indicates whether Device Fingerprinting Protected Auth endpoints are enabled in the SDK.
      - on_challenge: OnChallenge is the action to take when a DFPPA "challenge" verdict is returned.
    """  # noqa

    enabled: Optional[DFPPASetting] = None
    on_challenge: Optional[DFPPAOnChallengeAction] = None


class B2BMagicLinksConfig(pydantic.BaseModel):
    """
    Fields:
      - enabled: Indicates whether Magic Links endpoints are enabled in the SDK.
      - pkce_required: Indicates that PKCE is required in auth flows for the related SDK endpoints. PKCE increases security by introducing a one-time secret for each auth flow to ensure the user starts and completes each auth flow from the same application on the device. This prevents a malicious app from intercepting a redirect and authenticating with the user's token. PKCE is enabled by default for mobile SDKs.
    """  # noqa

    enabled: bool
    pkce_required: bool


class B2BOAuthConfig(pydantic.BaseModel):
    """
    Fields:
      - enabled: Indicates whether OAuth endpoints are enabled in the SDK.
      - pkce_required: Indicates that PKCE is required in auth flows for the related SDK endpoints. PKCE increases security by introducing a one-time secret for each auth flow to ensure the user starts and completes each auth flow from the same application on the device. This prevents a malicious app from intercepting a redirect and authenticating with the user's token. PKCE is enabled by default for mobile SDKs.
    """  # noqa

    enabled: bool
    pkce_required: bool


class B2BPasswordsConfig(pydantic.BaseModel):
    """
    Fields:
      - enabled: Indicates whether Passwords endpoints are enabled in the SDK.
      - pkce_required_for_password_resets: PKCERequired indicates whether PKCE is required for password resets. PKCE increases security by introducing a one-time secret for each auth flow to ensure the user starts and completes each auth flow from the same application on the device. This prevents a malicious app from intercepting a redirect and authenticating with the user's token. PKCE is enabled by default for mobile SDKs.
    """  # noqa

    enabled: bool
    pkce_required_for_password_resets: bool


class B2BSSOConfig(pydantic.BaseModel):
    """
    Fields:
      - enabled: Indicates whether SSO endpoints are enabled in the SDK.
      - pkce_required: Indicates that PKCE is required in auth flows for the related SDK endpoints. PKCE increases security by introducing a one-time secret for each auth flow to ensure the user starts and completes each auth flow from the same application on the device. This prevents a malicious app from intercepting a redirect and authenticating with the user's token. PKCE is enabled by default for mobile SDKs.
    """  # noqa

    enabled: bool
    pkce_required: bool


class B2BSessionsConfig(pydantic.BaseModel):
    """
    Fields:
      - max_session_duration_minutes: MaxSessionDurationMinutes is the maximum session duration that can be created in minutes.
    """  # noqa

    max_session_duration_minutes: int


class B2BTOTPsConfig(pydantic.BaseModel):
    """
    Fields:
      - create_totps: CreateTOTPs indicates whether TOTP creation is enabled in the SDK.
      - enabled: Indicates whether TOTP endpoints are enabled in the SDK.
    """  # noqa

    create_totps: bool
    enabled: bool


class ConsumerBasicConfig(pydantic.BaseModel):
    """
    Fields:
      - enabled: Enabled indicates whether the consumer project SDK is enabled. This allows the SDK to manage user and session data.
      - domains: Domains is a list of domains authorized for use in the SDK.
      - bundle_ids: BundleIDs is a list of bundle IDs authorized for use in the SDK.
    """  # noqa

    enabled: bool
    domains: List[str]
    bundle_ids: List[str]


class ConsumerBiometricsConfig(pydantic.BaseModel):
    """
    Fields:
      - create_biometrics_enabled: CreateBiometricsEnabled indicates whether biometrics creation is enabled in the SDK.
      - enabled: Enabled indicates whether the consumer project SDK is enabled. This allows the SDK to manage user and session data.
    """  # noqa

    create_biometrics_enabled: bool
    enabled: bool


class ConsumerCookiesConfig(pydantic.BaseModel):
    """
    Fields:
      - http_only: Specifies whether cookies should be set with the HttpOnly flag.
    """  # noqa

    http_only: ConsumerCookiesConfigHttpOnly


class ConsumerCryptoWalletsConfig(pydantic.BaseModel):
    """
    Fields:
      - enabled: Indicates whether Crypto Wallets endpoints are enabled in the SDK.
      - siwe_required: SIWERequired indicates whether Sign In With Ethereum is required for Crypto Wallets.
    """  # noqa

    enabled: bool
    siwe_required: bool


class ConsumerDFPPAConfig(pydantic.BaseModel):
    """
    Fields:
      - enabled: Indicates whether Device Fingerprinting Protected Auth endpoints are enabled in the SDK.
      - on_challenge: OnChallenge is the action to take when a DFPPA "challenge" verdict is returned.
    """  # noqa

    enabled: Optional[DFPPASetting] = None
    on_challenge: Optional[DFPPAOnChallengeAction] = None


class ConsumerMagicLinksConfig(pydantic.BaseModel):
    """
    Fields:
      - login_or_create_enabled: LoginOrCreateEnabled indicates whether login-or-create with magic links is enabled in the SDK.
      - send_enabled: SendEnabled indicates whether the magic links send endpoint is enabled in the SDK.
      - pkce_required: Indicates that PKCE is required in auth flows for the related SDK endpoints. PKCE increases security by introducing a one-time secret for each auth flow to ensure the user starts and completes each auth flow from the same application on the device. This prevents a malicious app from intercepting a redirect and authenticating with the user's token. PKCE is enabled by default for mobile SDKs.
    """  # noqa

    login_or_create_enabled: bool
    send_enabled: bool
    pkce_required: bool


class ConsumerOAuthConfig(pydantic.BaseModel):
    """
    Fields:
      - enabled: Indicates whether OAuth endpoints are enabled in the SDK.
      - pkce_required: Indicates that PKCE is required in auth flows for the related SDK endpoints. PKCE increases security by introducing a one-time secret for each auth flow to ensure the user starts and completes each auth flow from the same application on the device. This prevents a malicious app from intercepting a redirect and authenticating with the user's token. PKCE is enabled by default for mobile SDKs.
    """  # noqa

    enabled: bool
    pkce_required: bool


class ConsumerPasswordsConfig(pydantic.BaseModel):
    """
    Fields:
      - enabled: Indicates whether Passwords endpoints are enabled in the SDK.
      - pkce_required_for_password_resets: PKCERequired indicates whether PKCE is required for password resets. PKCE increases security by introducing a one-time secret for each auth flow to ensure the user starts and completes each auth flow from the same application on the device. This prevents a malicious app from intercepting a redirect and authenticating with the user's token. PKCE is enabled by default for mobile SDKs.
    """  # noqa

    enabled: bool
    pkce_required_for_password_resets: bool


class ConsumerSessionsConfig(pydantic.BaseModel):
    """
    Fields:
      - max_session_duration_minutes: MaxSessionDurationMinutes is the maximum session duration that can be created in minutes.
    """  # noqa

    max_session_duration_minutes: int


class ConsumerTOTPsConfig(pydantic.BaseModel):
    """
    Fields:
      - create_totps: CreateTOTPs indicates whether TOTP creation is enabled in the SDK.
      - enabled: Indicates whether TOTP endpoints are enabled in the SDK.
    """  # noqa

    create_totps: bool
    enabled: bool


class ConsumerWebAuthnConfig(pydantic.BaseModel):
    """
    Fields:
      - create_webauthns: (no documentation yet)
      - enabled: Indicates whether WebAuthn endpoints are enabled in the SDK.
    """  # noqa

    create_webauthns: bool
    enabled: bool


class SMSAutofillMetadata(pydantic.BaseModel):
    """
    Fields:
      - metadata_type: MetadataType is the type of metadata to use for autofill. This should be either "domain" or "hash".
      - metadata_value: MetadataValue is the value of the metadata to use for autofill. This should be the associated domain name (for MetadataType "domain") or application hash (for MetadataType "hash").
      - bundle_id: BundleID is the ID of the bundle to use for autofill. This should be the associated bundle ID.
    """  # noqa

    metadata_type: SMSAutofillMetadataMetadataType
    metadata_value: str
    bundle_id: str


class B2BOTPsConfig(pydantic.BaseModel):
    """
    Fields:
      - sms_enabled: SMSEnabled indicates whether the SMS OTP endpoints are enabled in the SDK.
      - sms_autofill_metadata: SMSAutofillMetadata is a list of metadata that can be used for autofill of SMS OTPs.
      - email_enabled: EmailEnabled indicates whether the email OTP endpoints are enabled in the SDK.
    """  # noqa

    sms_enabled: bool
    sms_autofill_metadata: List[SMSAutofillMetadata]
    email_enabled: bool


class B2BConfig(pydantic.BaseModel):
    """
    Fields:
      - basic: The basic configuration for the SDK. This includes enabling the SDK.
      - sessions: The session configuration for the SDK.
      - magic_links: The magic links configuration for the SDK.
      - oauth: The OAuth configuration for the SDK.
      - totps: TOTPs is the TOTPs configuration for the SDK.
      - sso: SSO is the SSO configuration for the B2B project SDK.
      - otps: OTPs is the OTPs configuration for the SDK.
      - dfppa: DFPPA is the Device Fingerprinting Protected Auth configuration for the SDK.
      - passwords: Passwords is the passwords configuration for the SDK.
      - cookies: Cookies is the cookies configuration for the SDK.
    """  # noqa

    basic: Optional[B2BBasicConfig] = None
    sessions: Optional[B2BSessionsConfig] = None
    magic_links: Optional[B2BMagicLinksConfig] = None
    oauth: Optional[B2BOAuthConfig] = None
    totps: Optional[B2BTOTPsConfig] = None
    sso: Optional[B2BSSOConfig] = None
    otps: Optional[B2BOTPsConfig] = None
    dfppa: Optional[B2BDFPPAConfig] = None
    passwords: Optional[B2BPasswordsConfig] = None
    cookies: Optional[B2BCookiesConfig] = None


class ConsumerOTPsConfig(pydantic.BaseModel):
    """
    Fields:
      - sms_login_or_create_enabled: SMSLoginOrCreateEnabled indicates whether the SMS OTP login or create endpoint is enabled in the SDK.
      - whatsapp_login_or_create_enabled: WhatsAppLoginOrCreateEnabled indicates whether the WhatsApp OTP login or create endpoint is enabled in the SDK.
      - email_login_or_create_enabled: EmailLoginOrCreateEnabled indicates whether the email OTP login or create endpoint is enabled in the SDK.
      - sms_send_enabled: SMSSendEnabled indicates whether the SMS OTP send endpoint is enabled in the SDK.
      - whatsapp_send_enabled: WhatsAppSendEnabled indicates whether the WhatsApp OTP send endpoint is enabled in the SDK.
      - email_send_enabled: EmailSendEnabled indicates whether the email OTP send endpoint is enabled in the SDK.
      - sms_autofill_metadata: SMSAutofillMetadata is a list of metadata that can be used for autofill of SMS OTPs.
    """  # noqa

    sms_login_or_create_enabled: bool
    whatsapp_login_or_create_enabled: bool
    email_login_or_create_enabled: bool
    sms_send_enabled: bool
    whatsapp_send_enabled: bool
    email_send_enabled: bool
    sms_autofill_metadata: List[SMSAutofillMetadata]


class ConsumerConfig(pydantic.BaseModel):
    """
    Fields:
      - basic: The basic configuration for the SDK. This includes enabling the SDK.
      - sessions: The session configuration for the SDK.
      - magic_links: The magic links configuration for the SDK.
      - otps: OTPs is the OTPs configuration for the SDK.
      - oauth: The OAuth configuration for the SDK.
      - totps: TOTPs is the TOTPs configuration for the SDK.
      - webauthn: WebAuthn is the WebAuthn configuration for the SDK.
      - crypto_wallets: CryptoWallets is the Crypto Wallets configuration for the SDK.
      - dfppa: DFPPA is the Device Fingerprinting Protected Auth configuration for the SDK.
      - biometrics: Biometrics is the biometrics configuration for the SDK.
      - passwords: Passwords is the passwords configuration for the SDK.
      - cookies: Cookies is the cookies configuration for the SDK.
    """  # noqa

    basic: Optional[ConsumerBasicConfig] = None
    sessions: Optional[ConsumerSessionsConfig] = None
    magic_links: Optional[ConsumerMagicLinksConfig] = None
    otps: Optional[ConsumerOTPsConfig] = None
    oauth: Optional[ConsumerOAuthConfig] = None
    totps: Optional[ConsumerTOTPsConfig] = None
    webauthn: Optional[ConsumerWebAuthnConfig] = None
    crypto_wallets: Optional[ConsumerCryptoWalletsConfig] = None
    dfppa: Optional[ConsumerDFPPAConfig] = None
    biometrics: Optional[ConsumerBiometricsConfig] = None
    passwords: Optional[ConsumerPasswordsConfig] = None
    cookies: Optional[ConsumerCookiesConfig] = None


class GetB2BConfigResponse(pydantic.BaseModel):
    """Response type for `SDK.get_b2_b_config`.
    Fields:
      - request_id: RequestID is a unique identifier to help with debugging the request.
      - config: Config is the SDK configuration.
      - status_code: StatusCode is the HTTP status code for the response.
    """  # noqa

    request_id: str
    config: B2BConfig
    status_code: int


class GetConsumerConfigResponse(pydantic.BaseModel):
    """Response type for `SDK.get_consumer_config`.
    Fields:
      - request_id: RequestID is a unique identifier to help with debugging the request.
      - config: Config is the SDK configuration.
      - status_code: StatusCode is the HTTP status code for the response.
    """  # noqa

    request_id: str
    config: ConsumerConfig
    status_code: int


class SetB2BConfigResponse(pydantic.BaseModel):
    """Response type for `SDK.set_b2_b_config`.
    Fields:
      - request_id: RequestID is a unique identifier to help with debugging the request.
      - config: Config is the SDK configuration.
      - status_code: StatusCode is the HTTP status code for the response.
    """  # noqa

    request_id: str
    config: B2BConfig
    status_code: int


class SetConsumerConfigResponse(pydantic.BaseModel):
    """Response type for `SDK.set_consumer_config`.
    Fields:
      - request_id: RequestID is a unique identifier to help with debugging the request.
      - config: Config is the SDK configuration.
      - status_code: StatusCode is the HTTP status code for the response.
    """  # noqa

    request_id: str
    config: ConsumerConfig
    status_code: int
