#!/usr/bin/env python3

# !!!
# WARNING: This file is autogenerated
# Only modify code within MANUAL() sections
# or your changes may be overwritten later!
# !!!


from __future__ import annotations

from typing import List, Optional

import pydantic


class MaskedSecret(pydantic.BaseModel):
    """
    Fields:
      - secret_id: The unique ID of the secret in the project.
      - last_four: LastFour is the last four characters of the secret.
      - created_at: The ISO-8601 timestamp for when the resource was created.
      - used_at: The ISO-8601 timestamp for when the secret was last used.
    """  # noqa

    secret_id: str
    last_four: str
    created_at: Optional[str] = None
    used_at: Optional[str] = None


class Secret(pydantic.BaseModel):
    """
    Fields:
      - secret_id: The unique ID of the secret in the project.
      - secret: The secret value. This is only visible once upon secret creation.
      - created_at: The ISO-8601 timestamp for when the resource was created.
    """  # noqa

    secret_id: str
    secret: str
    created_at: Optional[str] = None


class CreateResponse(pydantic.BaseModel):
    """Response type for `Secrets.create`.
    Fields:
      - request_id: RequestID is a unique identifier to help with debugging the request.
      - secret: The secret object that was created.
      - status_code: StatusCode is the HTTP status code for the response.
    """  # noqa

    request_id: str
    secret: Secret
    status_code: int


class DeleteResponse(pydantic.BaseModel):
    """Response type for `Secrets.delete`.
    Fields:
      - request_id: RequestID is a unique identifier to help with debugging the request.
      - status_code: StatusCode is the HTTP status code for the response.
    """  # noqa

    request_id: str
    status_code: int


class GetAllResponse(pydantic.BaseModel):
    """Response type for `Secrets.get_all`.
    Fields:
      - request_id: RequestID is a unique identifier to help with debugging the request.
      - secrets: Secrets is all the secrets that belong to the project.
      - status_code: StatusCode is the HTTP status code for the response.
    """  # noqa

    request_id: str
    secrets: List[MaskedSecret]
    status_code: int


class GetResponse(pydantic.BaseModel):
    """Response type for `Secrets.get`.
    Fields:
      - request_id: RequestID is a unique identifier to help with debugging the request.
      - secret: The secret object with the secret value masked.
      - status_code: StatusCode is the HTTP status code for the response.
    """  # noqa

    request_id: str
    secret: MaskedSecret
    status_code: int
