#!/usr/bin/env python3

# !!!
# WARNING: This file is autogenerated
# Only modify code within MANUAL() sections
# or your changes may be overwritten later!
# !!!


from __future__ import annotations

from enum import Enum
from typing import Any, Dict, List, Optional

import pydantic


class PublicKeyType(str, Enum):
    """PublicKeyType enum."""

    UNSPECIFIED = "UNSPECIFIED"
    JWK = "JWK"
    PEM = "PEM"


class PEMFile(pydantic.BaseModel):
    """
    Fields:
      - pem_file_id: PEMFileID is the unique identifier for the PEM file.
      - public_key: PublicKey is the public key content.
    """  # noqa

    pem_file_id: str
    public_key: str


class TrustedTokenProfile(pydantic.BaseModel):
    """
    Fields:
      - profile_id: ProfileID is the unique identifier for the trusted token profile.
      - name: Name is a human-readable name. This does not have to be unique.
      - audience: Audience is the audience for the trusted token profile.
      - issuer: Issuer is the issuer for the trusted token profile.
      - pem_files: PEMFiles is a list of PEM files.
      - can_jit_provision: CanJITProvision indicates whether the trusted token profile can be provisioned JIT.
      - jwks_url: JwksURL is the JWKS URL for the trusted token profile.
      - attribute_mapping: AttributeMapping is the attribute mapping for the trusted token profile.
      - public_key_type: PublicKeyType is the type of public key.
    """  # noqa

    profile_id: str
    name: str
    audience: str
    issuer: str
    pem_files: List[PEMFile]
    can_jit_provision: bool
    jwks_url: Optional[str] = None
    attribute_mapping: Optional[Dict[str, Any]] = None
    public_key_type: Optional[PublicKeyType] = None


class CreatePEMFileResponse(pydantic.BaseModel):
    """Response type for `TrustedTokenProfiles.create_pem_file`.
    Fields:
      - request_id: RequestID is a unique identifier to help with debugging the request.
      - pem_file: PEMFile is the PEM file that was created.
      - status_code: StatusCode is the HTTP status code for the response.
    """  # noqa

    request_id: str
    pem_file: PEMFile
    status_code: int


class CreateResponse(pydantic.BaseModel):
    """Response type for `TrustedTokenProfiles.create`.
    Fields:
      - request_id: RequestID is a unique identifier to help with debugging the request.
      - profile: TrustedTokenProfile is the trusted token profile that was created.
      - status_code: StatusCode is the HTTP status code for the response.
    """  # noqa

    request_id: str
    profile: TrustedTokenProfile
    status_code: int


class DeletePEMFileResponse(pydantic.BaseModel):
    """Response type for `TrustedTokenProfiles.delete_pem_file`.
    Fields:
      - request_id: RequestID is a unique identifier to help with debugging the request.
      - status_code: StatusCode is the HTTP status code for the response.
    """  # noqa

    request_id: str
    status_code: int


class DeleteResponse(pydantic.BaseModel):
    """Response type for `TrustedTokenProfiles.delete`.
    Fields:
      - request_id: RequestID is a unique identifier to help with debugging the request.
      - status_code: StatusCode is the HTTP status code for the response.
    """  # noqa

    request_id: str
    status_code: int


class GetAllResponse(pydantic.BaseModel):
    """Response type for `TrustedTokenProfiles.get_all`.
    Fields:
      - request_id: RequestID is a unique identifier to help with debugging the request.
      - profiles: A list of all trusted token profiles for the project.
      - status_code: StatusCode is the HTTP status code for the response.
    """  # noqa

    request_id: str
    profiles: List[TrustedTokenProfile]
    status_code: int


class GetPEMFileResponse(pydantic.BaseModel):
    """Response type for `TrustedTokenProfiles.get_pem_file`.
    Fields:
      - request_id: RequestID is a unique identifier to help with debugging the request.
      - pem_file: PEMFile is the PEM file that was retrieved.
      - status_code: StatusCode is the HTTP status code for the response.
    """  # noqa

    request_id: str
    pem_file: PEMFile
    status_code: int


class GetResponse(pydantic.BaseModel):
    """Response type for `TrustedTokenProfiles.get`.
    Fields:
      - request_id: RequestID is a unique identifier to help with debugging the request.
      - profile: TrustedTokenProfile is the trusted token profile.
      - status_code: StatusCode is the HTTP status code for the response.
    """  # noqa

    request_id: str
    profile: TrustedTokenProfile
    status_code: int


class UpdateResponse(pydantic.BaseModel):
    """Response type for `TrustedTokenProfiles.update`.
    Fields:
      - request_id: RequestID is a unique identifier to help with debugging the request.
      - profile: TrustedTokenProfile is the trusted token profile that was updated.
      - status_code: StatusCode is the HTTP status code for the response.
    """  # noqa

    request_id: str
    profile: TrustedTokenProfile
    status_code: int
