#!/usr/bin/env python3

# !!!
# WARNING: This file is autogenerated
# Only modify code within MANUAL() sections
# or your changes may be overwritten later!
# !!!


from typing import Optional

import requests
from stytch_management.country_code_allowlist import CountryCodeAllowlist
from stytch_management.emailtemplates import EmailTemplates
from stytch_management.environments import Environments
from stytch_management.event_log_streaming import EventLogStreaming
from stytch_management.http_client import DEFAULT_BASE_URL, HTTPClient
from stytch_management.jwttemplates import JWTTemplates
from stytch_management.passwordstrengthconfig import PasswordStrengthConfig
from stytch_management.projects import Projects
from stytch_management.publictokens import PublicTokens
from stytch_management.rbacpolicy import RBACPolicy
from stytch_management.redirecturls import RedirectURLs
from stytch_management.sdk import SDK
from stytch_management.secrets import Secrets
from stytch_management.trustedtokenprofiles import TrustedTokenProfiles


class Client:
    """
    Main client for interacting with the Stytch Management API.

    This client provides access to all Stytch Management API resources for programmatic
    workspace actions.

    Example:
        >>> from stytch_management import Client
        >>> client = Client(
        ...     workspace_key_id="workspace-test-...",
        ...     workspace_key_secret="secret-test-..."
        ... )
        >>> projects = client.projects.get_all()
    """

    def __init__(
        self,
        workspace_key_id: str,
        workspace_key_secret: str,
        base_url: str = DEFAULT_BASE_URL,
        timeout: int = 30,
        session: Optional[requests.Session] = None,
    ):
        """
        Initialize a new ManagementClient.

        Args:
            workspace_key_id: Your Stytch workspace key ID
            workspace_key_secret: Your Stytch workspace key secret
            base_url: Base URL for the Stytch Management API (defaults to production)
            timeout: Request timeout in seconds (default: 30)
            session: Optional requests.Session for connection pooling

        Raises:
            ValueError: If workspace_key_id or workspace_key_secret is missing
            ValueError: If base_url doesn't use HTTPS scheme
        """
        if not workspace_key_id:
            raise ValueError('Missing "workspace_key_id"')
        if not workspace_key_secret:
            raise ValueError('Missing "workspace_key_secret"')

        if not base_url.startswith("https://"):
            raise ValueError("base_url must use HTTPS scheme")

        # Ensure base_url ends with a trailing slash
        if not base_url.endswith("/"):
            base_url = base_url + "/"

        self._http_client = HTTPClient(
            workspace_key_id=workspace_key_id,
            workspace_key_secret=workspace_key_secret,
            base_url=base_url,
            timeout=timeout,
            session=session,
        )

        # Resource clients
        self.projects = Projects(self._http_client)
        self.country_code_allowlist = CountryCodeAllowlist(self._http_client)
        self.email_templates = EmailTemplates(self._http_client)
        self.environments = Environments(self._http_client)
        self.event_log_streaming = EventLogStreaming(self._http_client)
        self.jwt_templates = JWTTemplates(self._http_client)
        self.password_strength_config = PasswordStrengthConfig(self._http_client)
        self.public_tokens = PublicTokens(self._http_client)
        self.rbac_policy = RBACPolicy(self._http_client)
        self.redirect_urls = RedirectURLs(self._http_client)
        self.sdk = SDK(self._http_client)
        self.secrets = Secrets(self._http_client)
        self.trusted_token_profiles = TrustedTokenProfiles(self._http_client)
