# !!!
# WARNING: This file is autogenerated
# Only modify code within MANUAL() sections
# or your changes may be overwritten later!
# !!!

from __future__ import annotations

from typing import Any, Dict

from stytch_management.errors import ClientError
from stytch_management.http_client import HTTPClient
from stytch_management.models.country_code_allowlist import (
    GetAllowedSMSCountryCodesResponse,
    GetAllowedWhatsAppCountryCodesResponse,
    SetAllowedSMSCountryCodesResponse,
    SetAllowedWhatsAppCountryCodesResponse,
)


class CountryCodeAllowlist:
    """Resource client for CountryCodeAllowlist operations."""

    def __init__(self, http_client: HTTPClient) -> None:
        self._http_client = http_client

    def get_allowed_sms_country_codes(
        self,
        project_slug: str,
        environment_slug: str,
    ) -> GetAllowedSMSCountryCodesResponse:
        """GetAllowedSMSCountryCodes retrieves the allowed SMS country codes for an environment.

        Fields:
          - project_slug: ProjectSlug is the slug of the project for which to retrieve allowed SMS country codes.
          - environment_slug: EnvironmentSlug is the slug of the environment for which to retrieve allowed SMS country codes.
        """
        if not project_slug:
            raise ClientError("MISSING_PATH_PARAMETER", "project_slug cannot be empty")
        if not environment_slug:
            raise ClientError(
                "MISSING_PATH_PARAMETER", "environment_slug cannot be empty"
            )
        data: Dict[str, Any] = {}

        # Build URL with path parameters
        path = "/pwa/v3/projects/${project_slug}/environments/${environment_slug}/allowed_country_codes/sms"
        path = path.replace("${project_slug}", str(project_slug))
        path = path.replace("${environment_slug}", str(environment_slug))

        params: Dict[str, Any] = {}
        response_json = self._http_client.get(path, params=params if params else None)

        return GetAllowedSMSCountryCodesResponse(**response_json)

    def get_allowed_whatsapp_country_codes(
        self,
        project_slug: str,
        environment_slug: str,
    ) -> GetAllowedWhatsAppCountryCodesResponse:
        """GetAllowedWhatsAppCountryCodes retrieves the allowed WhatsApp country codes for an environment.

        Fields:
          - project_slug: ProjectSlug is the slug of the project.
          - environment_slug: EnvironmentSlug is the slug of the environment.
        """
        if not project_slug:
            raise ClientError("MISSING_PATH_PARAMETER", "project_slug cannot be empty")
        if not environment_slug:
            raise ClientError(
                "MISSING_PATH_PARAMETER", "environment_slug cannot be empty"
            )
        data: Dict[str, Any] = {}

        # Build URL with path parameters
        path = "/pwa/v3/projects/${project_slug}/environments/${environment_slug}/allowed_country_codes/whatsapp"
        path = path.replace("${project_slug}", str(project_slug))
        path = path.replace("${environment_slug}", str(environment_slug))

        params: Dict[str, Any] = {}
        response_json = self._http_client.get(path, params=params if params else None)

        return GetAllowedWhatsAppCountryCodesResponse(**response_json)

    def set_allowed_sms_country_codes(
        self,
        project_slug: str,
        environment_slug: str,
        country_codes: List[str],
    ) -> SetAllowedSMSCountryCodesResponse:
        """SetAllowedSMSCountryCodes sets the allowed SMS country codes for an environment.

        Fields:
          - project_slug: ProjectSlug is the slug of the project.
          - environment_slug: EnvironmentSlug is the slug of the environment.
          - country_codes: A list of country codes to set as allowed for SMS.
        """
        if not project_slug:
            raise ClientError("MISSING_PATH_PARAMETER", "project_slug cannot be empty")
        if not environment_slug:
            raise ClientError(
                "MISSING_PATH_PARAMETER", "environment_slug cannot be empty"
            )
        data: Dict[str, Any] = {}
        data["country_codes"] = country_codes

        # Build URL with path parameters
        path = "/pwa/v3/projects/${project_slug}/environments/${environment_slug}/allowed_country_codes/sms"
        path = path.replace("${project_slug}", str(project_slug))
        path = path.replace("${environment_slug}", str(environment_slug))

        response_json = self._http_client.post(path, json=data if data else None)

        return SetAllowedSMSCountryCodesResponse(**response_json)

    def set_allowed_whatsapp_country_codes(
        self,
        project_slug: str,
        environment_slug: str,
        country_codes: List[str],
    ) -> SetAllowedWhatsAppCountryCodesResponse:
        """SetAllowedWhatsAppCountryCodes sets the allowed WhatsApp country codes for an environment.

        Fields:
          - project_slug: ProjectSlug is the slug of the project.
          - environment_slug: EnvironmentSlug is the slug of the environment.
          - country_codes: A list of country codes to set as allowed for WhatsApp.
        """
        if not project_slug:
            raise ClientError("MISSING_PATH_PARAMETER", "project_slug cannot be empty")
        if not environment_slug:
            raise ClientError(
                "MISSING_PATH_PARAMETER", "environment_slug cannot be empty"
            )
        data: Dict[str, Any] = {}
        data["country_codes"] = country_codes

        # Build URL with path parameters
        path = "/pwa/v3/projects/${project_slug}/environments/${environment_slug}/allowed_country_codes/whatsapp"
        path = path.replace("${project_slug}", str(project_slug))
        path = path.replace("${environment_slug}", str(environment_slug))

        response_json = self._http_client.post(path, json=data if data else None)

        return SetAllowedWhatsAppCountryCodesResponse(**response_json)
