# !!!
# WARNING: This file is autogenerated
# Only modify code within MANUAL() sections
# or your changes may be overwritten later!
# !!!

from __future__ import annotations

from typing import Any, Dict, Optional

from stytch_management.errors import ClientError
from stytch_management.http_client import HTTPClient
from stytch_management.models.emailtemplates import (
    CreateResponse,
    CustomHTMLCustomization,
    DeleteResponse,
    GetAllResponse,
    GetDefaultResponse,
    GetResponse,
    PrebuiltCustomization,
    SenderInformation,
    SetDefaultResponse,
    UnsetDefaultResponse,
    UpdateResponse,
)


class EmailTemplates:
    """Resource client for EmailTemplates operations."""

    def __init__(self, http_client: HTTPClient) -> None:
        self._http_client = http_client

    def create(
        self,
        project_slug: str,
        template_id: str,
        name: Optional[str] = None,
        sender_information: Optional[Union[SenderInformation, Dict[str, Any]]] = None,
        prebuilt_customization: Optional[
            Union[PrebuiltCustomization, Dict[str, Any]]
        ] = None,
        custom_html_customization: Optional[
            Union[CustomHTMLCustomization, Dict[str, Any]]
        ] = None,
    ) -> CreateResponse:
        """Create creates an email template for a project.

        Fields:
          - project_slug: ProjectSlug is the slug of the project.
          - template_id: TemplateID is a unique identifier to use for the template – this is how you will refer to the template when sending emails from your project or managing this template. It can never be changed after creation.
          - name: Name is a human-readable name. This does not have to be unique.
          - sender_information: SenderInformation is information about the email sender, such as the reply address or rendered name. This is an optional field for PrebuiltCustomization, but required for CustomHTMLCustomization.
          - prebuilt_customization: PrebuiltCustomization is customization related to prebuilt fields (such as button color) for prebuilt email templates.
          - custom_html_customization: CustomHTMLCustomization is customization defined for completely custom HTML email templates.
        """
        if not project_slug:
            raise ClientError("MISSING_PATH_PARAMETER", "project_slug cannot be empty")
        data: Dict[str, Any] = {}
        data["template_id"] = template_id
        if name is not None:
            data["name"] = name
        if sender_information is not None:
            data["sender_information"] = (
                sender_information
                if isinstance(sender_information, dict)
                else sender_information.dict()
            )
        if prebuilt_customization is not None:
            data["prebuilt_customization"] = (
                prebuilt_customization
                if isinstance(prebuilt_customization, dict)
                else prebuilt_customization.dict()
            )
        if custom_html_customization is not None:
            data["custom_html_customization"] = (
                custom_html_customization
                if isinstance(custom_html_customization, dict)
                else custom_html_customization.dict()
            )

        # Build URL with path parameters
        path = "/pwa/v3/projects/${project_slug}/email_templates"
        path = path.replace("${project_slug}", str(project_slug))

        response_json = self._http_client.post(path, json=data if data else None)

        return CreateResponse(**response_json)

    def get(
        self,
        project_slug: str,
        template_id: str,
    ) -> GetResponse:
        """Get retrieves an email template for a project.

        Fields:
          - project_slug: ProjectSlug is the slug of the project.
          - template_id: TemplateID is a unique identifier to use for the template – this is how you will refer to the template when sending emails from your project or managing this template. It can never be changed after creation.
        """
        if not project_slug:
            raise ClientError("MISSING_PATH_PARAMETER", "project_slug cannot be empty")
        if not template_id:
            raise ClientError("MISSING_PATH_PARAMETER", "template_id cannot be empty")
        data: Dict[str, Any] = {}

        # Build URL with path parameters
        path = "/pwa/v3/projects/${project_slug}/email_templates/${template_id}"
        path = path.replace("${project_slug}", str(project_slug))
        path = path.replace("${template_id}", str(template_id))

        params: Dict[str, Any] = {}
        response_json = self._http_client.get(path, params=params if params else None)

        return GetResponse(**response_json)

    def get_all(
        self,
        project_slug: str,
    ) -> GetAllResponse:
        """GetAll retrieves all email templates for a project.

        Fields:
          - project_slug: ProjectSlug is the slug of the project.
        """
        if not project_slug:
            raise ClientError("MISSING_PATH_PARAMETER", "project_slug cannot be empty")
        data: Dict[str, Any] = {}

        # Build URL with path parameters
        path = "/pwa/v3/projects/${project_slug}/email_templates"
        path = path.replace("${project_slug}", str(project_slug))

        params: Dict[str, Any] = {}
        response_json = self._http_client.get(path, params=params if params else None)

        return GetAllResponse(**response_json)

    def update(
        self,
        project_slug: str,
        template_id: str,
        name: Optional[str] = None,
        sender_information: Optional[Union[SenderInformation, Dict[str, Any]]] = None,
        prebuilt_customization: Optional[
            Union[PrebuiltCustomization, Dict[str, Any]]
        ] = None,
        custom_html_customization: Optional[
            Union[CustomHTMLCustomization, Dict[str, Any]]
        ] = None,
    ) -> UpdateResponse:
        """Update updates an email template for a project.

        Fields:
          - project_slug: ProjectSlug is the slug of the project.
          - template_id: TemplateID is a unique identifier to use for the template – this is how you will refer to the template when sending emails from your project or managing this template. It can never be changed after creation.
          - name: Name is a human-readable name. This does not have to be unique.
          - sender_information: SenderInformation is information about the email sender, such as the reply address or rendered name. This is an optional field for PrebuiltCustomization, but required for CustomHTMLCustomization.
          - prebuilt_customization: PrebuiltCustomization is customization related to prebuilt fields (such as button color) for prebuilt email templates.
          - custom_html_customization: CustomHTMLCustomization is customization defined for completely custom HTML email templates.
        """
        if not project_slug:
            raise ClientError("MISSING_PATH_PARAMETER", "project_slug cannot be empty")
        if not template_id:
            raise ClientError("MISSING_PATH_PARAMETER", "template_id cannot be empty")
        data: Dict[str, Any] = {}
        if name is not None:
            data["name"] = name
        if sender_information is not None:
            data["sender_information"] = (
                sender_information
                if isinstance(sender_information, dict)
                else sender_information.dict()
            )
        if prebuilt_customization is not None:
            data["prebuilt_customization"] = (
                prebuilt_customization
                if isinstance(prebuilt_customization, dict)
                else prebuilt_customization.dict()
            )
        if custom_html_customization is not None:
            data["custom_html_customization"] = (
                custom_html_customization
                if isinstance(custom_html_customization, dict)
                else custom_html_customization.dict()
            )

        # Build URL with path parameters
        path = "/pwa/v3/projects/${project_slug}/email_templates/${template_id}"
        path = path.replace("${project_slug}", str(project_slug))
        path = path.replace("${template_id}", str(template_id))

        response_json = self._http_client.put(path, json=data if data else None)

        return UpdateResponse(**response_json)

    def delete(
        self,
        project_slug: str,
        template_id: str,
    ) -> DeleteResponse:
        """Delete deletes an email template for a project.

        Fields:
          - project_slug: ProjectSlug is the slug of the project.
          - template_id: TemplateID is a unique identifier to use for the template – this is how you will refer to the template when sending emails from your project or managing this template. It can never be changed after creation.
        """
        if not project_slug:
            raise ClientError("MISSING_PATH_PARAMETER", "project_slug cannot be empty")
        if not template_id:
            raise ClientError("MISSING_PATH_PARAMETER", "template_id cannot be empty")
        data: Dict[str, Any] = {}

        # Build URL with path parameters
        path = "/pwa/v3/projects/${project_slug}/email_templates/${template_id}"
        path = path.replace("${project_slug}", str(project_slug))
        path = path.replace("${template_id}", str(template_id))

        response_json = self._http_client.delete(path)

        return DeleteResponse(**response_json)

    def set_default(
        self,
        project_slug: str,
        template_id: str,
        email_template_type: Optional[Union[TemplateType, str]] = None,
    ) -> SetDefaultResponse:
        """SetDefault sets the default email template for a specific template type in a project.

        Fields:
          - project_slug: ProjectSlug is the slug of the project.
          - template_id: TemplateID is a unique identifier to use for the template – this is how you will refer to the template when sending emails from your project or managing this template. It can never be changed after creation.
          - email_template_type: EmailTemplateType is the template type.
        """
        if not project_slug:
            raise ClientError("MISSING_PATH_PARAMETER", "project_slug cannot be empty")
        if not email_template_type:
            raise ClientError(
                "MISSING_PATH_PARAMETER", "email_template_type cannot be empty"
            )
        data: Dict[str, Any] = {}
        data["template_id"] = template_id

        # Build URL with path parameters
        path = "/pwa/v3/projects/${project_slug}/default_email_templates/${email_template_type}"
        path = path.replace("${project_slug}", str(project_slug))
        path = path.replace("${email_template_type}", str(email_template_type))

        response_json = self._http_client.post(path, json=data if data else None)

        return SetDefaultResponse(**response_json)

    def get_default(
        self,
        project_slug: str,
        email_template_type: Optional[Union[TemplateType, str]] = None,
    ) -> GetDefaultResponse:
        """GetDefault retrieves the default email template for a specific template type in a project.

        Fields:
          - project_slug: ProjectSlug is the slug of the project to retrieve.
          - email_template_type: EmailTemplateType is the template type for which to get the default email template.
        """
        if not project_slug:
            raise ClientError("MISSING_PATH_PARAMETER", "project_slug cannot be empty")
        if not email_template_type:
            raise ClientError(
                "MISSING_PATH_PARAMETER", "email_template_type cannot be empty"
            )
        data: Dict[str, Any] = {}

        # Build URL with path parameters
        path = "/pwa/v3/projects/${project_slug}/default_email_templates/${email_template_type}"
        path = path.replace("${project_slug}", str(project_slug))
        path = path.replace("${email_template_type}", str(email_template_type))

        params: Dict[str, Any] = {}
        response_json = self._http_client.get(path, params=params if params else None)

        return GetDefaultResponse(**response_json)

    def unset_default(
        self,
        project_slug: str,
        email_template_type: Optional[Union[TemplateType, str]] = None,
    ) -> UnsetDefaultResponse:
        """UnsetDefault removes the default email template for a specific template type in a project.

        Fields:
          - project_slug: ProjectSlug is the slug of the project for which to unset the default email template.
          - email_template_type: EmailTemplateType is the template type for which to unset the default email template. Note that unsetting the PREBUILT type is not supported.
        """
        if not project_slug:
            raise ClientError("MISSING_PATH_PARAMETER", "project_slug cannot be empty")
        if not email_template_type:
            raise ClientError(
                "MISSING_PATH_PARAMETER", "email_template_type cannot be empty"
            )
        data: Dict[str, Any] = {}

        # Build URL with path parameters
        path = "/pwa/v3/projects/${project_slug}/default_email_templates/${email_template_type}"
        path = path.replace("${project_slug}", str(project_slug))
        path = path.replace("${email_template_type}", str(email_template_type))

        response_json = self._http_client.delete(path)

        return UnsetDefaultResponse(**response_json)
