# !!!
# WARNING: This file is autogenerated
# Only modify code within MANUAL() sections
# or your changes may be overwritten later!
# !!!

from __future__ import annotations

from typing import Any, Dict, Optional

from stytch_management.errors import ClientError
from stytch_management.http_client import HTTPClient
from stytch_management.models.environments import (
    CreateResponse,
    DeleteResponse,
    GetAllResponse,
    GetMetricsResponse,
    GetResponse,
    UpdateResponse,
)


class Environments:
    """Resource client for Environments operations."""

    def __init__(self, http_client: HTTPClient) -> None:
        self._http_client = http_client

    def create(
        self,
        project_slug: str,
        name: str,
        type: Optional[Union[EnvironmentType, str]] = None,
        environment_slug: Optional[str] = None,
        cross_org_passwords_enabled: Optional[bool] = None,
        user_impersonation_enabled: Optional[bool] = None,
        zero_downtime_session_migration_url: Optional[str] = None,
        user_lock_self_serve_enabled: Optional[bool] = None,
        user_lock_threshold: Optional[int] = None,
        user_lock_ttl: Optional[int] = None,
        idp_authorization_url: Optional[str] = None,
        idp_dynamic_client_registration_enabled: Optional[bool] = None,
        idp_dynamic_client_registration_access_token_template_content: Optional[
            str
        ] = None,
    ) -> CreateResponse:
        """Creates a new environment in a project.

        Fields:
          - project_slug: ProjectSlug is the slug of the project.
          - name: Name is a human-readable name. This does not have to be unique.
          - type: The environment's type.
          - environment_slug: EnvironmentSlug is the slug of the environment.
          - cross_org_passwords_enabled: CrossOrgPasswordsEnabled indicates whether the environment uses cross-org passwords.
          - user_impersonation_enabled: Indicates whether user impersonation is enabled for the environment.
          - zero_downtime_session_migration_url: ZeroDowntimeSessionMigrationURL is the OIDC-compliant UserInfo endpoint for session migration.
          - user_lock_self_serve_enabled: Indicates whether users in the environment who get locked out should automatically get an unlock email magic link.
          - user_lock_threshold: UserLockThreshold represents the number of failed authenticate attempts that will cause a user in the environment to be locked. Defaults to 10.
          - user_lock_ttl: Represents the time in seconds that the user in the environment remains locked once the lock is set. Defaults to 1 hour (3600 seconds).
          - idp_authorization_url: The OpenID Configuration endpoint for Connected Apps for the environment.
          - idp_dynamic_client_registration_enabled: IDPDynamicClientRegistrationEnabled indicates whether the project has opted in to Dynamic Client Registration (DCR) for Connected Apps.
          - idp_dynamic_client_registration_access_token_template_content: IDPDynamicClientRegistrationAccessTokenTemplateContent is the access token template to use for clients created through Dynamic Client Registration (DCR).
        """
        if not project_slug:
            raise ClientError("MISSING_PATH_PARAMETER", "project_slug cannot be empty")
        data: Dict[str, Any] = {}
        data["name"] = name
        if type is not None:
            data["type"] = type
        if environment_slug is not None:
            data["environment_slug"] = environment_slug
        if cross_org_passwords_enabled is not None:
            data["cross_org_passwords_enabled"] = cross_org_passwords_enabled
        if user_impersonation_enabled is not None:
            data["user_impersonation_enabled"] = user_impersonation_enabled
        if zero_downtime_session_migration_url is not None:
            data["zero_downtime_session_migration_url"] = (
                zero_downtime_session_migration_url
            )
        if user_lock_self_serve_enabled is not None:
            data["user_lock_self_serve_enabled"] = user_lock_self_serve_enabled
        if user_lock_threshold is not None:
            data["user_lock_threshold"] = user_lock_threshold
        if user_lock_ttl is not None:
            data["user_lock_ttl"] = user_lock_ttl
        if idp_authorization_url is not None:
            data["idp_authorization_url"] = idp_authorization_url
        if idp_dynamic_client_registration_enabled is not None:
            data["idp_dynamic_client_registration_enabled"] = (
                idp_dynamic_client_registration_enabled
            )
        if idp_dynamic_client_registration_access_token_template_content is not None:
            data["idp_dynamic_client_registration_access_token_template_content"] = (
                idp_dynamic_client_registration_access_token_template_content
            )

        # Build URL with path parameters
        path = "/pwa/v3/projects/${project_slug}/environments"
        path = path.replace("${project_slug}", str(project_slug))

        response_json = self._http_client.post(path, json=data if data else None)

        return CreateResponse(**response_json)

    def get(
        self,
        project_slug: str,
        environment_slug: str,
    ) -> GetResponse:
        """Retrieves an environment.

        Fields:
          - project_slug: ProjectSlug is the slug of the project.
          - environment_slug: EnvironmentSlug is the slug of the environment.
        """
        if not project_slug:
            raise ClientError("MISSING_PATH_PARAMETER", "project_slug cannot be empty")
        if not environment_slug:
            raise ClientError(
                "MISSING_PATH_PARAMETER", "environment_slug cannot be empty"
            )
        data: Dict[str, Any] = {}

        # Build URL with path parameters
        path = "/pwa/v3/projects/${project_slug}/environments/${environment_slug}"
        path = path.replace("${project_slug}", str(project_slug))
        path = path.replace("${environment_slug}", str(environment_slug))

        params: Dict[str, Any] = {}
        response_json = self._http_client.get(path, params=params if params else None)

        return GetResponse(**response_json)

    def get_all(
        self,
        project_slug: str,
    ) -> GetAllResponse:
        """Retrieves all environments in a project.

        Fields:
          - project_slug: ProjectSlug is the slug of the project.
        """
        if not project_slug:
            raise ClientError("MISSING_PATH_PARAMETER", "project_slug cannot be empty")
        data: Dict[str, Any] = {}

        # Build URL with path parameters
        path = "/pwa/v3/projects/${project_slug}/environments"
        path = path.replace("${project_slug}", str(project_slug))

        params: Dict[str, Any] = {}
        response_json = self._http_client.get(path, params=params if params else None)

        return GetAllResponse(**response_json)

    def update(
        self,
        project_slug: str,
        environment_slug: str,
        name: Optional[str] = None,
        cross_org_passwords_enabled: Optional[bool] = None,
        user_impersonation_enabled: Optional[bool] = None,
        zero_downtime_session_migration_url: Optional[str] = None,
        use_custom_domain_in_magic_link_emails: Optional[bool] = None,
        user_lock_self_serve_enabled: Optional[bool] = None,
        user_lock_threshold: Optional[int] = None,
        user_lock_ttl: Optional[int] = None,
        idp_authorization_url: Optional[str] = None,
        idp_dynamic_client_registration_enabled: Optional[bool] = None,
        idp_dynamic_client_registration_access_token_template_content: Optional[
            str
        ] = None,
    ) -> UpdateResponse:
        """Updates the environment.

        Fields:
          - project_slug: ProjectSlug is the slug of the project.
          - environment_slug: EnvironmentSlug is the slug of the environment.
          - name: Name is a human-readable name. This does not have to be unique.
          - cross_org_passwords_enabled: CrossOrgPasswordsEnabled indicates whether the environment uses cross-org passwords.
          - user_impersonation_enabled: Indicates whether user impersonation is enabled for the environment.
          - zero_downtime_session_migration_url: ZeroDowntimeSessionMigrationURL is the OIDC-compliant UserInfo endpoint for session migration.
          - use_custom_domain_in_magic_link_emails: (no documentation yet)
          - user_lock_self_serve_enabled: Indicates whether users in the environment who get locked out should automatically get an unlock email magic link.
          - user_lock_threshold: UserLockThreshold represents the number of failed authenticate attempts that will cause a user in the environment to be locked. Defaults to 10.
          - user_lock_ttl: Represents the time in seconds that the user in the environment remains locked once the lock is set. Defaults to 1 hour (3600 seconds).
          - idp_authorization_url: The OpenID Configuration endpoint for Connected Apps for the environment.
          - idp_dynamic_client_registration_enabled: IDPDynamicClientRegistrationEnabled indicates whether the project has opted in to Dynamic Client Registration (DCR) for Connected Apps.
          - idp_dynamic_client_registration_access_token_template_content: IDPDynamicClientRegistrationAccessTokenTemplateContent is the access token template to use for clients created through Dynamic Client Registration (DCR).
        """
        if not project_slug:
            raise ClientError("MISSING_PATH_PARAMETER", "project_slug cannot be empty")
        if not environment_slug:
            raise ClientError(
                "MISSING_PATH_PARAMETER", "environment_slug cannot be empty"
            )
        data: Dict[str, Any] = {}
        if name is not None:
            data["name"] = name
        if cross_org_passwords_enabled is not None:
            data["cross_org_passwords_enabled"] = cross_org_passwords_enabled
        if user_impersonation_enabled is not None:
            data["user_impersonation_enabled"] = user_impersonation_enabled
        if zero_downtime_session_migration_url is not None:
            data["zero_downtime_session_migration_url"] = (
                zero_downtime_session_migration_url
            )
        if use_custom_domain_in_magic_link_emails is not None:
            data["use_custom_domain_in_magic_link_emails"] = (
                use_custom_domain_in_magic_link_emails
            )
        if user_lock_self_serve_enabled is not None:
            data["user_lock_self_serve_enabled"] = user_lock_self_serve_enabled
        if user_lock_threshold is not None:
            data["user_lock_threshold"] = user_lock_threshold
        if user_lock_ttl is not None:
            data["user_lock_ttl"] = user_lock_ttl
        if idp_authorization_url is not None:
            data["idp_authorization_url"] = idp_authorization_url
        if idp_dynamic_client_registration_enabled is not None:
            data["idp_dynamic_client_registration_enabled"] = (
                idp_dynamic_client_registration_enabled
            )
        if idp_dynamic_client_registration_access_token_template_content is not None:
            data["idp_dynamic_client_registration_access_token_template_content"] = (
                idp_dynamic_client_registration_access_token_template_content
            )

        # Build URL with path parameters
        path = "/pwa/v3/projects/${project_slug}/environments/${environment_slug}"
        path = path.replace("${project_slug}", str(project_slug))
        path = path.replace("${environment_slug}", str(environment_slug))

        response_json = self._http_client.patch(path, json=data if data else None)

        return UpdateResponse(**response_json)

    def delete(
        self,
        project_slug: str,
        environment_slug: str,
    ) -> DeleteResponse:
        """Deletes an environment.

        Fields:
          - project_slug: ProjectSlug is the slug of the project.
          - environment_slug: EnvironmentSlug is the slug of the environment.
        """
        if not project_slug:
            raise ClientError("MISSING_PATH_PARAMETER", "project_slug cannot be empty")
        if not environment_slug:
            raise ClientError(
                "MISSING_PATH_PARAMETER", "environment_slug cannot be empty"
            )
        data: Dict[str, Any] = {}

        # Build URL with path parameters
        path = "/pwa/v3/projects/${project_slug}/environments/${environment_slug}"
        path = path.replace("${project_slug}", str(project_slug))
        path = path.replace("${environment_slug}", str(environment_slug))

        response_json = self._http_client.delete(path)

        return DeleteResponse(**response_json)

    def get_metrics(
        self,
        project_slug: str,
        environment_slug: str,
    ) -> GetMetricsResponse:
        """Retrieves metrics for an environment.

        Fields:
          - project_slug: ProjectSlug is the slug of the project.
          - environment_slug: EnvironmentSlug is the slug of the environment.
        """
        if not project_slug:
            raise ClientError("MISSING_PATH_PARAMETER", "project_slug cannot be empty")
        if not environment_slug:
            raise ClientError(
                "MISSING_PATH_PARAMETER", "environment_slug cannot be empty"
            )
        data: Dict[str, Any] = {}

        # Build URL with path parameters
        path = (
            "/pwa/v3/projects/${project_slug}/environments/${environment_slug}/metrics"
        )
        path = path.replace("${project_slug}", str(project_slug))
        path = path.replace("${environment_slug}", str(environment_slug))

        params: Dict[str, Any] = {}
        response_json = self._http_client.get(path, params=params if params else None)

        return GetMetricsResponse(**response_json)
