# !!!
# WARNING: This file is autogenerated
# Only modify code within MANUAL() sections
# or your changes may be overwritten later!
# !!!

from __future__ import annotations

from typing import Any, Dict, Optional

from stytch_management.errors import ClientError
from stytch_management.http_client import HTTPClient
from stytch_management.models.event_log_streaming import (
    CreateResponse,
    DeleteResponse,
    DestinationConfig,
    DisableResponse,
    EnableResponse,
    EventLogStreaming,
    GetResponse,
    UpdateResponse,
)


class EventLogStreaming:
    """Resource client for EventLogStreaming operations."""

    def __init__(self, http_client: HTTPClient) -> None:
        self._http_client = http_client

    def get(
        self,
        project_slug: str,
        environment_slug: str,
        destination_type: Optional[Union[DestinationType, str]] = None,
    ) -> GetResponse:
        """Get retrieves an event log streaming config for an environment.

        Fields:
          - project_slug: ProjectSlug is the slug of the project.
          - environment_slug: EnvironmentSlug is the slug of the environment.
          - destination_type: DestinationType is the type of destination to which to send events.
        """
        if not project_slug:
            raise ClientError("MISSING_PATH_PARAMETER", "project_slug cannot be empty")
        if not environment_slug:
            raise ClientError(
                "MISSING_PATH_PARAMETER", "environment_slug cannot be empty"
            )
        if not destination_type:
            raise ClientError(
                "MISSING_PATH_PARAMETER", "destination_type cannot be empty"
            )
        data: Dict[str, Any] = {}

        # Build URL with path parameters
        path = "/pwa/v3/projects/${project_slug}/environments/${environment_slug}/event_log_streaming/${destination_type}"
        path = path.replace("${project_slug}", str(project_slug))
        path = path.replace("${environment_slug}", str(environment_slug))
        path = path.replace("${destination_type}", str(destination_type))

        params: Dict[str, Any] = {}
        response_json = self._http_client.get(path, params=params if params else None)

        return GetResponse(**response_json)

    def create(
        self,
        project_slug: str,
        environment_slug: str,
        destination_type: Optional[Union[DestinationType, str]] = None,
        destination_config: Optional[Union[DestinationConfig, Dict[str, Any]]] = None,
    ) -> CreateResponse:
        """Create creates an event log streaming config for an environment.

        Fields:
          - project_slug: ProjectSlug is the slug of the project.
          - environment_slug: EnvironmentSlug is the slug of the environment.
          - destination_type: DestinationType is the type of destination to which to send events.
          - destination_config: DestinationConfig is the configuration for the destination to which to send events.
        """
        if not project_slug:
            raise ClientError("MISSING_PATH_PARAMETER", "project_slug cannot be empty")
        if not environment_slug:
            raise ClientError(
                "MISSING_PATH_PARAMETER", "environment_slug cannot be empty"
            )
        data: Dict[str, Any] = {}
        if destination_type is not None:
            data["destination_type"] = destination_type
        if destination_config is not None:
            data["destination_config"] = (
                destination_config
                if isinstance(destination_config, dict)
                else destination_config.dict()
            )

        # Build URL with path parameters
        path = "/pwa/v3/projects/${project_slug}/environments/${environment_slug}/event_log_streaming"
        path = path.replace("${project_slug}", str(project_slug))
        path = path.replace("${environment_slug}", str(environment_slug))

        response_json = self._http_client.post(path, json=data if data else None)

        return CreateResponse(**response_json)

    def update(
        self,
        project_slug: str,
        environment_slug: str,
        destination_type: Optional[Union[DestinationType, str]] = None,
        destination_config: Optional[Union[DestinationConfig, Dict[str, Any]]] = None,
    ) -> UpdateResponse:
        """Update updates an event log streaming config for an environment.

        Fields:
          - project_slug: ProjectSlug is the slug of the project.
          - environment_slug: EnvironmentSlug is the slug of the environment.
          - destination_type: DestinationType is the type of destination to which to send events.
          - destination_config: DestinationConfig is the configuration for the destination to which to send events.
        """
        if not project_slug:
            raise ClientError("MISSING_PATH_PARAMETER", "project_slug cannot be empty")
        if not environment_slug:
            raise ClientError(
                "MISSING_PATH_PARAMETER", "environment_slug cannot be empty"
            )
        if not destination_type:
            raise ClientError(
                "MISSING_PATH_PARAMETER", "destination_type cannot be empty"
            )
        data: Dict[str, Any] = {}
        if destination_config is not None:
            data["destination_config"] = (
                destination_config
                if isinstance(destination_config, dict)
                else destination_config.dict()
            )

        # Build URL with path parameters
        path = "/pwa/v3/projects/${project_slug}/environments/${environment_slug}/event_log_streaming/${destination_type}"
        path = path.replace("${project_slug}", str(project_slug))
        path = path.replace("${environment_slug}", str(environment_slug))
        path = path.replace("${destination_type}", str(destination_type))

        response_json = self._http_client.put(path, json=data if data else None)

        return UpdateResponse(**response_json)

    def delete(
        self,
        project_slug: str,
        environment_slug: str,
        destination_type: Optional[Union[DestinationType, str]] = None,
    ) -> DeleteResponse:
        """Delete deletes an event log streaming config for an environment.

        Fields:
          - project_slug: ProjectSlug is the slug of the project.
          - environment_slug: EnvironmentSlug is the slug of the environment.
          - destination_type: DestinationType is the type of destination to which to send events.
        """
        if not project_slug:
            raise ClientError("MISSING_PATH_PARAMETER", "project_slug cannot be empty")
        if not environment_slug:
            raise ClientError(
                "MISSING_PATH_PARAMETER", "environment_slug cannot be empty"
            )
        if not destination_type:
            raise ClientError(
                "MISSING_PATH_PARAMETER", "destination_type cannot be empty"
            )
        data: Dict[str, Any] = {}

        # Build URL with path parameters
        path = "/pwa/v3/projects/${project_slug}/environments/${environment_slug}/event_log_streaming/${destination_type}"
        path = path.replace("${project_slug}", str(project_slug))
        path = path.replace("${environment_slug}", str(environment_slug))
        path = path.replace("${destination_type}", str(destination_type))

        response_json = self._http_client.delete(path)

        return DeleteResponse(**response_json)

    def enable(
        self,
        project_slug: str,
        environment_slug: str,
        destination_type: Optional[Union[DestinationType, str]] = None,
    ) -> EnableResponse:
        """Enable starts streaming event logs for an environment to a destination.

        Fields:
          - project_slug: ProjectSlug is the slug of the project.
          - environment_slug: EnvironmentSlug is the slug of the environment.
          - destination_type: DestinationType is the type of destination to which to send events.
        """
        if not project_slug:
            raise ClientError("MISSING_PATH_PARAMETER", "project_slug cannot be empty")
        if not environment_slug:
            raise ClientError(
                "MISSING_PATH_PARAMETER", "environment_slug cannot be empty"
            )
        if not destination_type:
            raise ClientError(
                "MISSING_PATH_PARAMETER", "destination_type cannot be empty"
            )
        data: Dict[str, Any] = {}

        # Build URL with path parameters
        path = "/pwa/v3/projects/${project_slug}/environments/${environment_slug}/event_log_streaming/${destination_type}/enable"
        path = path.replace("${project_slug}", str(project_slug))
        path = path.replace("${environment_slug}", str(environment_slug))
        path = path.replace("${destination_type}", str(destination_type))

        response_json = self._http_client.post(path, json=data if data else None)

        return EnableResponse(**response_json)

    def disable(
        self,
        project_slug: str,
        environment_slug: str,
        destination_type: Optional[Union[DestinationType, str]] = None,
    ) -> DisableResponse:
        """Disable stops streaming event logs for an environment to a destination.

        Fields:
          - project_slug: ProjectSlug is the slug of the project.
          - environment_slug: EnvironmentSlug is the slug of the environment.
          - destination_type: DestinationType is the type of destination to which to send events.
        """
        if not project_slug:
            raise ClientError("MISSING_PATH_PARAMETER", "project_slug cannot be empty")
        if not environment_slug:
            raise ClientError(
                "MISSING_PATH_PARAMETER", "environment_slug cannot be empty"
            )
        if not destination_type:
            raise ClientError(
                "MISSING_PATH_PARAMETER", "destination_type cannot be empty"
            )
        data: Dict[str, Any] = {}

        # Build URL with path parameters
        path = "/pwa/v3/projects/${project_slug}/environments/${environment_slug}/event_log_streaming/${destination_type}/disable"
        path = path.replace("${project_slug}", str(project_slug))
        path = path.replace("${environment_slug}", str(environment_slug))
        path = path.replace("${destination_type}", str(destination_type))

        response_json = self._http_client.post(path, json=data if data else None)

        return DisableResponse(**response_json)
