# !!!
# WARNING: This file is autogenerated
# Only modify code within MANUAL() sections
# or your changes may be overwritten later!
# !!!

from __future__ import annotations

from typing import Any, Dict, Optional

from stytch_management.errors import ClientError
from stytch_management.http_client import HTTPClient
from stytch_management.models.jwttemplates import GetResponse, SetResponse


class JWTTemplates:
    """Resource client for JWTTemplates operations."""

    def __init__(self, http_client: HTTPClient) -> None:
        self._http_client = http_client

    def get(
        self,
        project_slug: str,
        environment_slug: str,
        jwt_template_type: Optional[Union[JWTTemplateType, str]] = None,
    ) -> GetResponse:
        """Get retrieves a JWT template for a project

        Fields:
          - project_slug: ProjectSlug is the slug of the project.
          - environment_slug: EnvironmentSlug is the slug of the environment.
          - jwt_template_type: JWTTemplateType is the type of JWT template.
        """
        if not project_slug:
            raise ClientError("MISSING_PATH_PARAMETER", "project_slug cannot be empty")
        if not environment_slug:
            raise ClientError(
                "MISSING_PATH_PARAMETER", "environment_slug cannot be empty"
            )
        if not jwt_template_type:
            raise ClientError(
                "MISSING_PATH_PARAMETER", "jwt_template_type cannot be empty"
            )
        data: Dict[str, Any] = {}

        # Build URL with path parameters
        path = "/pwa/v3/projects/${project_slug}/environments/${environment_slug}/jwt_templates/${jwt_template_type}"
        path = path.replace("${project_slug}", str(project_slug))
        path = path.replace("${environment_slug}", str(environment_slug))
        path = path.replace("${jwt_template_type}", str(jwt_template_type))

        params: Dict[str, Any] = {}
        response_json = self._http_client.get(path, params=params if params else None)

        return GetResponse(**response_json)

    def set(
        self,
        project_slug: str,
        environment_slug: str,
        template_content: str,
        custom_audience: str,
        jwt_template_type: Optional[Union[JWTTemplateType, str]] = None,
    ) -> SetResponse:
        """Set updates a specific JWT template for a project

        Fields:
          - project_slug: ProjectSlug is the slug of the project.
          - environment_slug: EnvironmentSlug is the slug of the environment.
          - template_content: TemplateContent is the JWT template content.
          - custom_audience: CustomAudience is an optional custom audience for the JWT template.
          - jwt_template_type: JWTTemplateType is the type of JWT template.
        """
        if not project_slug:
            raise ClientError("MISSING_PATH_PARAMETER", "project_slug cannot be empty")
        if not environment_slug:
            raise ClientError(
                "MISSING_PATH_PARAMETER", "environment_slug cannot be empty"
            )
        if not jwt_template_type:
            raise ClientError(
                "MISSING_PATH_PARAMETER", "jwt_template_type cannot be empty"
            )
        data: Dict[str, Any] = {}
        data["template_content"] = template_content
        data["custom_audience"] = custom_audience

        # Build URL with path parameters
        path = "/pwa/v3/projects/${project_slug}/environments/${environment_slug}/jwt_templates/${jwt_template_type}"
        path = path.replace("${project_slug}", str(project_slug))
        path = path.replace("${environment_slug}", str(environment_slug))
        path = path.replace("${jwt_template_type}", str(jwt_template_type))

        response_json = self._http_client.put(path, json=data if data else None)

        return SetResponse(**response_json)
