# !!!
# WARNING: This file is autogenerated
# Only modify code within MANUAL() sections
# or your changes may be overwritten later!
# !!!

from __future__ import annotations

from typing import Any, Dict, Optional

from stytch_management.errors import ClientError
from stytch_management.http_client import HTTPClient
from stytch_management.models.passwordstrengthconfig import (
    GetResponse,
    PasswordStrengthConfig,
    SetResponse,
)


class PasswordStrengthConfig:
    """Resource client for PasswordStrengthConfig operations."""

    def __init__(self, http_client: HTTPClient) -> None:
        self._http_client = http_client

    def get(
        self,
        project_slug: str,
        environment_slug: str,
    ) -> GetResponse:
        """Get retrieves the password strength configuration for an environment.

        Fields:
          - project_slug: ProjectSlug is the slug of the project.
          - environment_slug: EnvironmentSlug is the slug of the environment.
        """
        if not project_slug:
            raise ClientError("MISSING_PATH_PARAMETER", "project_slug cannot be empty")
        if not environment_slug:
            raise ClientError(
                "MISSING_PATH_PARAMETER", "environment_slug cannot be empty"
            )
        data: Dict[str, Any] = {}

        # Build URL with path parameters
        path = "/pwa/v3/projects/${project_slug}/environments/${environment_slug}/password_strength_config"
        path = path.replace("${project_slug}", str(project_slug))
        path = path.replace("${environment_slug}", str(environment_slug))

        params: Dict[str, Any] = {}
        response_json = self._http_client.get(path, params=params if params else None)

        return GetResponse(**response_json)

    def set(
        self,
        project_slug: str,
        environment_slug: str,
        check_breach_on_creation: bool,
        check_breach_on_authentication: bool,
        validate_on_authentication: bool,
        validation_policy: Optional[Union[ValidationPolicy, str]] = None,
        luds_min_password_length: Optional[int] = None,
        luds_min_password_complexity: Optional[int] = None,
    ) -> SetResponse:
        """Set updates the password strength configuration for an environment.

        Fields:
          - project_slug: ProjectSlug is the slug of the project.
          - environment_slug: EnvironmentSlug is the slug of the environment.
          - check_breach_on_creation: CheckBreachOnCreation is a flag to check whether to use the HaveIBeenPwned database to detect password breaches when a user first creates their password.
          - check_breach_on_authentication: CheckBreachOnAuthentication denotes whether to use the HaveIBeenPwned database to detect password breaches when a user authenticates.
          - validate_on_authentication: ValidateOnAuthentication notes whether to require a password reset on authentication if a user's current password no longer meets the project's current policy requirements.
          - validation_policy: ValidationPolicy is the policy to use for password validation.
          - luds_min_password_length: LudsMinPasswordLength is the minimum number of characters in a password if using a LUDS validation_policy. This field is nil when using the ZXCVBN validation_policy.
          - luds_min_password_complexity: LudsMinPasswordComplexity is the minimum number of "character types" in a password (Lowercase, Uppercase, Digits, Symbols) when using a LUDS validation_policy. This field is nil when using the ZXCVBN validation_policy.
        """
        if not project_slug:
            raise ClientError("MISSING_PATH_PARAMETER", "project_slug cannot be empty")
        if not environment_slug:
            raise ClientError(
                "MISSING_PATH_PARAMETER", "environment_slug cannot be empty"
            )
        data: Dict[str, Any] = {}
        data["check_breach_on_creation"] = check_breach_on_creation
        data["check_breach_on_authentication"] = check_breach_on_authentication
        data["validate_on_authentication"] = validate_on_authentication
        if validation_policy is not None:
            data["validation_policy"] = validation_policy
        if luds_min_password_length is not None:
            data["luds_min_password_length"] = luds_min_password_length
        if luds_min_password_complexity is not None:
            data["luds_min_password_complexity"] = luds_min_password_complexity

        # Build URL with path parameters
        path = "/pwa/v3/projects/${project_slug}/environments/${environment_slug}/password_strength_config"
        path = path.replace("${project_slug}", str(project_slug))
        path = path.replace("${environment_slug}", str(environment_slug))

        response_json = self._http_client.put(path, json=data if data else None)

        return SetResponse(**response_json)
