# !!!
# WARNING: This file is autogenerated
# Only modify code within MANUAL() sections
# or your changes may be overwritten later!
# !!!

from __future__ import annotations

from typing import Any, Dict, Optional

from stytch_management.errors import ClientError
from stytch_management.http_client import HTTPClient
from stytch_management.models.projects import (
    CreateResponse,
    DeleteResponse,
    GetAllResponse,
    GetResponse,
    UpdateResponse,
)


class Projects:
    """Resource client for Projects operations."""

    def __init__(self, http_client: HTTPClient) -> None:
        self._http_client = http_client

    def create(
        self,
        name: str,
        vertical: Optional[Union[Vertical, str]] = None,
        project_slug: Optional[str] = None,
    ) -> CreateResponse:
        """Create creates a project, including both a live and test environment.

        Fields:
          - name: Name is a human-readable name. This does not have to be unique.
          - vertical: Vertical is the project's vertical.
          - project_slug: The slug of the project.
        """
        data: Dict[str, Any] = {}
        data["name"] = name
        if vertical is not None:
            data["vertical"] = vertical
        if project_slug is not None:
            data["project_slug"] = project_slug

        path = "/pwa/v3/projects"

        response_json = self._http_client.post(path, json=data if data else None)

        return CreateResponse(**response_json)

    def get(
        self,
        project_slug: str,
    ) -> GetResponse:
        """Get retrieves a project.

        Fields:
          - project_slug: ProjectSlug is the slug of the project.
        """
        if not project_slug:
            raise ClientError("MISSING_PATH_PARAMETER", "project_slug cannot be empty")
        data: Dict[str, Any] = {}

        # Build URL with path parameters
        path = "/pwa/v3/projects/${project_slug}"
        path = path.replace("${project_slug}", str(project_slug))

        params: Dict[str, Any] = {}
        response_json = self._http_client.get(path, params=params if params else None)

        return GetResponse(**response_json)

    def get_all(
        self,
    ) -> GetAllResponse:
        """GetAll retrieves all projects in a workspace.

        Fields:
        """
        data: Dict[str, Any] = {}

        path = "/pwa/v3/projects"

        params: Dict[str, Any] = {}
        response_json = self._http_client.get(path, params=params if params else None)

        return GetAllResponse(**response_json)

    def update(
        self,
        project_slug: str,
        name: Optional[str] = None,
    ) -> UpdateResponse:
        """Update updates the project.

        Fields:
          - project_slug: ProjectSlug is the slug of the project.
          - name: Name is a human-readable name. This does not have to be unique.
        """
        if not project_slug:
            raise ClientError("MISSING_PATH_PARAMETER", "project_slug cannot be empty")
        data: Dict[str, Any] = {}
        if name is not None:
            data["name"] = name

        # Build URL with path parameters
        path = "/pwa/v3/projects/${project_slug}"
        path = path.replace("${project_slug}", str(project_slug))

        response_json = self._http_client.patch(path, json=data if data else None)

        return UpdateResponse(**response_json)

    def delete(
        self,
        project_slug: str,
    ) -> DeleteResponse:
        """Delete deletes a project and all of its environments.

        Fields:
          - project_slug: ProjectSlug is the slug of the project.
        """
        if not project_slug:
            raise ClientError("MISSING_PATH_PARAMETER", "project_slug cannot be empty")
        data: Dict[str, Any] = {}

        # Build URL with path parameters
        path = "/pwa/v3/projects/${project_slug}"
        path = path.replace("${project_slug}", str(project_slug))

        response_json = self._http_client.delete(path)

        return DeleteResponse(**response_json)
