# !!!
# WARNING: This file is autogenerated
# Only modify code within MANUAL() sections
# or your changes may be overwritten later!
# !!!

from __future__ import annotations

from typing import Any, Dict, Optional

from stytch_management.errors import ClientError
from stytch_management.http_client import HTTPClient
from stytch_management.models.rbacpolicy import (
    DefaultRole,
    GetResponse,
    Resource,
    Role,
    Scope,
    SetResponse,
)


class RBACPolicy:
    """Resource client for RBACPolicy operations."""

    def __init__(self, http_client: HTTPClient) -> None:
        self._http_client = http_client

    def get(
        self,
        project_slug: str,
        environment_slug: str,
    ) -> GetResponse:
        """Get retrieves the RBAC policy for an environment.

        Fields:
          - project_slug: ProjectSlug is the slug of the project.
          - environment_slug: EnvironmentSlug is the slug of the environment.
        """
        if not project_slug:
            raise ClientError("MISSING_PATH_PARAMETER", "project_slug cannot be empty")
        if not environment_slug:
            raise ClientError(
                "MISSING_PATH_PARAMETER", "environment_slug cannot be empty"
            )
        data: Dict[str, Any] = {}

        # Build URL with path parameters
        path = "/pwa/v3/projects/${project_slug}/environments/${environment_slug}/rbac_policy"
        path = path.replace("${project_slug}", str(project_slug))
        path = path.replace("${environment_slug}", str(environment_slug))

        params: Dict[str, Any] = {}
        response_json = self._http_client.get(path, params=params if params else None)

        return GetResponse(**response_json)

    def set(
        self,
        project_slug: str,
        environment_slug: str,
        stytch_member: Optional[Union[DefaultRole, Dict[str, Any]]] = None,
        stytch_admin: Optional[Union[DefaultRole, Dict[str, Any]]] = None,
        stytch_user: Optional[Union[DefaultRole, Dict[str, Any]]] = None,
        custom_roles: Optional[List[Union[Role, Dict[str, Any]]]] = None,
        custom_resources: Optional[List[Union[Resource, Dict[str, Any]]]] = None,
        custom_scopes: Optional[List[Union[Scope, Dict[str, Any]]]] = None,
    ) -> SetResponse:
        """Set updates the RBAC policy for an environment.

        Fields:
          - project_slug: ProjectSlug is the slug of the project.
          - environment_slug: EnvironmentSlug is the slug of the environment.
          - stytch_member: The following fields are valid for B2B projects only: StytchMember is the default role given to members within the environment. Only permissions are returned; role_id and description are managed by Stytch.
          - stytch_admin: StytchAdmin is the role assigned to admins within an organization. Only permissions are returned; role_id and description are managed by Stytch.
          - stytch_user: The following field is valid for Consumer projects only: StytchUser is the default role given to users within the environment. Only permissions are returned; role_id and description are managed by Stytch.
          - custom_roles: The following fields are valid for both B2B and Consumer projects: CustomRoles are additional roles that exist within the environment beyond the stytch_member, stytch_admin, or stytch_user roles.
          - custom_resources: CustomResources are resources that exist within the environment beyond those defined within the stytch_resources.
          - custom_scopes: CustomScopes are additional scopes that exist within the environment beyond those defined by default.
        """
        if not project_slug:
            raise ClientError("MISSING_PATH_PARAMETER", "project_slug cannot be empty")
        if not environment_slug:
            raise ClientError(
                "MISSING_PATH_PARAMETER", "environment_slug cannot be empty"
            )
        data: Dict[str, Any] = {}
        if stytch_member is not None:
            data["stytch_member"] = (
                stytch_member
                if isinstance(stytch_member, dict)
                else stytch_member.dict()
            )
        if stytch_admin is not None:
            data["stytch_admin"] = (
                stytch_admin if isinstance(stytch_admin, dict) else stytch_admin.dict()
            )
        if stytch_user is not None:
            data["stytch_user"] = (
                stytch_user if isinstance(stytch_user, dict) else stytch_user.dict()
            )
        if custom_roles is not None:
            data["custom_roles"] = [
                item if isinstance(item, dict) else item.dict() for item in custom_roles
            ]
        if custom_resources is not None:
            data["custom_resources"] = [
                item if isinstance(item, dict) else item.dict()
                for item in custom_resources
            ]
        if custom_scopes is not None:
            data["custom_scopes"] = [
                item if isinstance(item, dict) else item.dict()
                for item in custom_scopes
            ]

        # Build URL with path parameters
        path = "/pwa/v3/projects/${project_slug}/environments/${environment_slug}/rbac_policy"
        path = path.replace("${project_slug}", str(project_slug))
        path = path.replace("${environment_slug}", str(environment_slug))

        response_json = self._http_client.put(path, json=data if data else None)

        return SetResponse(**response_json)
