# !!!
# WARNING: This file is autogenerated
# Only modify code within MANUAL() sections
# or your changes may be overwritten later!
# !!!

from __future__ import annotations

from typing import Any, Dict, Optional

from stytch_management.errors import ClientError
from stytch_management.http_client import HTTPClient
from stytch_management.models.redirecturls import (
    CreateResponse,
    DeleteResponse,
    GetAllResponse,
    GetResponse,
    UpdateResponse,
    URLType,
)


class RedirectURLs:
    """Resource client for RedirectURLs operations."""

    def __init__(self, http_client: HTTPClient) -> None:
        self._http_client = http_client

    def create(
        self,
        project_slug: str,
        environment_slug: str,
        url: str,
        valid_types: Optional[List[Union[URLType, Dict[str, Any]]]] = None,
        do_not_promote_defaults: Optional[bool] = None,
    ) -> CreateResponse:
        """Create creates a redirect URL for an environment.

        Fields:
          - project_slug: ProjectSlug is the slug of the project.
          - environment_slug: EnvironmentSlug is the slug of the environment.
          - url: The URL to which to redirect.
          - valid_types: ValidTypes is a list of all the URLRedirectType available for this URL.
          - do_not_promote_defaults: DoNotPromoteDefaults is used to suppress the automatic "promotion" of a RedirectURL to the default if no other RedirectURL exists for the given type. This is primarily intended for use with stytchauth/terraform-provider-stytch to allow Terraform provisioning to be idempotent. For a Create request, the default behavior is to promote the RedirectURL to the default if no other RedirectURL exists for the given type, even if `IsDefault` was set to false.  WARNING: If this is set to true, it is possible to have valid RedirectURLs for a given type but *no* default RedirectURL for that type. If no default exists for a given type, using an API endpoint that uses redirect URLs (such as sending a magic link), you will need to explicitly specify which redirect URL should be used.
        """
        if not project_slug:
            raise ClientError("MISSING_PATH_PARAMETER", "project_slug cannot be empty")
        if not environment_slug:
            raise ClientError(
                "MISSING_PATH_PARAMETER", "environment_slug cannot be empty"
            )
        data: Dict[str, Any] = {}
        data["url"] = url
        if valid_types is not None:
            data["valid_types"] = [
                item if isinstance(item, dict) else item.dict() for item in valid_types
            ]
        if do_not_promote_defaults is not None:
            data["do_not_promote_defaults"] = do_not_promote_defaults

        # Build URL with path parameters
        path = "/pwa/v3/projects/${project_slug}/environments/${environment_slug}/redirect_urls"
        path = path.replace("${project_slug}", str(project_slug))
        path = path.replace("${environment_slug}", str(environment_slug))

        response_json = self._http_client.post(path, json=data if data else None)

        return CreateResponse(**response_json)

    def get(
        self,
        project_slug: str,
        environment_slug: str,
        url: str,
    ) -> GetResponse:
        """Get retrieves a redirect URL for an environment.

        Fields:
          - project_slug: ProjectSlug is the slug of the project.
          - environment_slug: EnvironmentSlug is the slug of the environment.
          - url: The URL to which to redirect.
        """
        if not project_slug:
            raise ClientError("MISSING_PATH_PARAMETER", "project_slug cannot be empty")
        if not environment_slug:
            raise ClientError(
                "MISSING_PATH_PARAMETER", "environment_slug cannot be empty"
            )
        data: Dict[str, Any] = {}

        # Build URL with path parameters
        path = "/pwa/v3/projects/${project_slug}/environments/${environment_slug}/redirect_urls"
        path = path.replace("${project_slug}", str(project_slug))
        path = path.replace("${environment_slug}", str(environment_slug))

        params: Dict[str, Any] = {}
        params["url"] = url
        response_json = self._http_client.get(path, params=params if params else None)

        return GetResponse(**response_json)

    def get_all(
        self,
        project_slug: str,
        environment_slug: str,
    ) -> GetAllResponse:
        """GetAll retrieves all redirect URLs for an environment.

        Fields:
          - project_slug: ProjectSlug is the slug of the project.
          - environment_slug: EnvironmentSlug is the slug of the environment.
        """
        if not project_slug:
            raise ClientError("MISSING_PATH_PARAMETER", "project_slug cannot be empty")
        if not environment_slug:
            raise ClientError(
                "MISSING_PATH_PARAMETER", "environment_slug cannot be empty"
            )
        data: Dict[str, Any] = {}

        # Build URL with path parameters
        path = "/pwa/v3/projects/${project_slug}/environments/${environment_slug}/redirect_urls/all"
        path = path.replace("${project_slug}", str(project_slug))
        path = path.replace("${environment_slug}", str(environment_slug))

        params: Dict[str, Any] = {}
        response_json = self._http_client.get(path, params=params if params else None)

        return GetAllResponse(**response_json)

    def update(
        self,
        project_slug: str,
        environment_slug: str,
        url: str,
        valid_types: Optional[List[Union[URLType, Dict[str, Any]]]] = None,
        do_not_promote_defaults: Optional[bool] = None,
    ) -> UpdateResponse:
        """Update updates the valid types for a redirect URL for an environment.

        Fields:
          - project_slug: ProjectSlug is the slug of the project.
          - environment_slug: EnvironmentSlug is the slug of the environment.
          - url: The URL to which to redirect.
          - valid_types: ValidTypes is a list of all the URLRedirectType available for this URL.
          - do_not_promote_defaults: DoNotPromoteDefaults is used to suppress the automatic "promotion" of a RedirectURL to the default if no other RedirectURL exists for the given type. This is primarily intended for use with stytchauth/terraform-provider-stytch to allow Terraform provisioning to be idempotent. For a Create request, the default behavior is to promote the RedirectURL to the default if no other RedirectURL exists for the given type, even if `IsDefault` was set to false.  WARNING: If this is set to true, it is possible to have valid RedirectURLs for a given type but *no* default RedirectURL for that type. If no default exists for a given type, using an API endpoint that uses redirect URLs (such as sending a magic link), you will need to explicitly specify which redirect URL should be used.
        """
        if not project_slug:
            raise ClientError("MISSING_PATH_PARAMETER", "project_slug cannot be empty")
        if not environment_slug:
            raise ClientError(
                "MISSING_PATH_PARAMETER", "environment_slug cannot be empty"
            )
        data: Dict[str, Any] = {}
        if valid_types is not None:
            data["valid_types"] = [
                item if isinstance(item, dict) else item.dict() for item in valid_types
            ]
        if do_not_promote_defaults is not None:
            data["do_not_promote_defaults"] = do_not_promote_defaults

        # Build URL with path parameters
        path = "/pwa/v3/projects/${project_slug}/environments/${environment_slug}/redirect_urls"
        path = path.replace("${project_slug}", str(project_slug))
        path = path.replace("${environment_slug}", str(environment_slug))

        params: Dict[str, Any] = {}
        params["url"] = url
        response_json = self._http_client.put(
            path, json=data if data else None, params=params if params else None
        )

        return UpdateResponse(**response_json)

    def delete(
        self,
        project_slug: str,
        environment_slug: str,
        url: str,
        do_not_promote_defaults: Optional[bool] = None,
    ) -> DeleteResponse:
        """Delete deletes a redirect URL for an environment.

        Fields:
          - project_slug: ProjectSlug is the slug of the project.
          - environment_slug: EnvironmentSlug is the slug of the environment.
          - url: The URL to which to redirect.
          - do_not_promote_defaults: DoNotPromoteDefaults is used to suppress the automatic "promotion" of a RedirectURL to the default if no other RedirectURL exists for the given type. This is primarily intended for use with stytchauth/terraform-provider-stytch to allow Terraform provisioning to be idempotent. For a Create request, the default behavior is to promote the RedirectURL to the default if no other RedirectURL exists for the given type, even if `IsDefault` was set to false.  WARNING: If this is set to true, it is possible to have valid RedirectURLs for a given type but *no* default RedirectURL for that type. If no default exists for a given type, using an API endpoint that uses redirect URLs (such as sending a magic link), you will need to explicitly specify which redirect URL should be used.
        """
        if not project_slug:
            raise ClientError("MISSING_PATH_PARAMETER", "project_slug cannot be empty")
        if not environment_slug:
            raise ClientError(
                "MISSING_PATH_PARAMETER", "environment_slug cannot be empty"
            )
        data: Dict[str, Any] = {}

        # Build URL with path parameters
        path = "/pwa/v3/projects/${project_slug}/environments/${environment_slug}/redirect_urls"
        path = path.replace("${project_slug}", str(project_slug))
        path = path.replace("${environment_slug}", str(environment_slug))

        params: Dict[str, Any] = {}
        params["url"] = url
        if do_not_promote_defaults is not None:
            params["do_not_promote_defaults"] = do_not_promote_defaults
        response_json = self._http_client.delete(
            path, params=params if params else None
        )

        return DeleteResponse(**response_json)
