# !!!
# WARNING: This file is autogenerated
# Only modify code within MANUAL() sections
# or your changes may be overwritten later!
# !!!

from __future__ import annotations

from typing import Any, Dict, Optional

from stytch_management.errors import ClientError
from stytch_management.http_client import HTTPClient
from stytch_management.models.sdk import (
    B2BConfig,
    ConsumerConfig,
    GetB2BConfigResponse,
    GetConsumerConfigResponse,
    SetB2BConfigResponse,
    SetConsumerConfigResponse,
)


class SDK:
    """Resource client for SDK operations."""

    def __init__(self, http_client: HTTPClient) -> None:
        self._http_client = http_client

    def get_consumer_config(
        self,
        project_slug: str,
        environment_slug: str,
    ) -> GetConsumerConfigResponse:
        """GetConsumerConfig retrieves the SDK configuration for a B2C project environment

        Fields:
          - project_slug: ProjectSlug is the slug of the project.
          - environment_slug: EnvironmentSlug is the slug of the environment.
        """
        if not project_slug:
            raise ClientError("MISSING_PATH_PARAMETER", "project_slug cannot be empty")
        if not environment_slug:
            raise ClientError(
                "MISSING_PATH_PARAMETER", "environment_slug cannot be empty"
            )
        data: Dict[str, Any] = {}

        # Build URL with path parameters
        path = "/pwa/v3/projects/${project_slug}/environments/${environment_slug}/sdk/consumer"
        path = path.replace("${project_slug}", str(project_slug))
        path = path.replace("${environment_slug}", str(environment_slug))

        params: Dict[str, Any] = {}
        response_json = self._http_client.get(path, params=params if params else None)

        return GetConsumerConfigResponse(**response_json)

    def set_consumer_config(
        self,
        project_slug: str,
        environment_slug: str,
        config: Optional[Union[ConsumerConfig, Dict[str, Any]]] = None,
    ) -> SetConsumerConfigResponse:
        """SetConsumerConfig updates the SDK configuration for a B2C project environment

        Fields:
          - project_slug: ProjectSlug is the slug of the project.
          - environment_slug: EnvironmentSlug is the slug of the environment.
          - config: Config is the SDK configuration.
        """
        if not project_slug:
            raise ClientError("MISSING_PATH_PARAMETER", "project_slug cannot be empty")
        if not environment_slug:
            raise ClientError(
                "MISSING_PATH_PARAMETER", "environment_slug cannot be empty"
            )
        data: Dict[str, Any] = {}
        if config is not None:
            data["config"] = config if isinstance(config, dict) else config.dict()

        # Build URL with path parameters
        path = "/pwa/v3/projects/${project_slug}/environments/${environment_slug}/sdk/consumer"
        path = path.replace("${project_slug}", str(project_slug))
        path = path.replace("${environment_slug}", str(environment_slug))

        response_json = self._http_client.put(path, json=data if data else None)

        return SetConsumerConfigResponse(**response_json)

    def get_b2_b_config(
        self,
        project_slug: str,
        environment_slug: str,
    ) -> GetB2BConfigResponse:
        """GetB2BConfig retrieves the SDK configuration for a B2B project environment

        Fields:
          - project_slug: ProjectSlug is the slug of the project.
          - environment_slug: EnvironmentSlug is the slug of the environment.
        """
        if not project_slug:
            raise ClientError("MISSING_PATH_PARAMETER", "project_slug cannot be empty")
        if not environment_slug:
            raise ClientError(
                "MISSING_PATH_PARAMETER", "environment_slug cannot be empty"
            )
        data: Dict[str, Any] = {}

        # Build URL with path parameters
        path = (
            "/pwa/v3/projects/${project_slug}/environments/${environment_slug}/sdk/b2b"
        )
        path = path.replace("${project_slug}", str(project_slug))
        path = path.replace("${environment_slug}", str(environment_slug))

        params: Dict[str, Any] = {}
        response_json = self._http_client.get(path, params=params if params else None)

        return GetB2BConfigResponse(**response_json)

    def set_b2_b_config(
        self,
        project_slug: str,
        environment_slug: str,
        config: Optional[Union[B2BConfig, Dict[str, Any]]] = None,
    ) -> SetB2BConfigResponse:
        """SetB2BConfig updates the SDK configuration for a B2B project environment

        Fields:
          - project_slug: ProjectSlug is the slug of the project.
          - environment_slug: EnvironmentSlug is the slug of the environment.
          - config: Config is the SDK configuration.
        """
        if not project_slug:
            raise ClientError("MISSING_PATH_PARAMETER", "project_slug cannot be empty")
        if not environment_slug:
            raise ClientError(
                "MISSING_PATH_PARAMETER", "environment_slug cannot be empty"
            )
        data: Dict[str, Any] = {}
        if config is not None:
            data["config"] = config if isinstance(config, dict) else config.dict()

        # Build URL with path parameters
        path = (
            "/pwa/v3/projects/${project_slug}/environments/${environment_slug}/sdk/b2b"
        )
        path = path.replace("${project_slug}", str(project_slug))
        path = path.replace("${environment_slug}", str(environment_slug))

        response_json = self._http_client.put(path, json=data if data else None)

        return SetB2BConfigResponse(**response_json)
