# !!!
# WARNING: This file is autogenerated
# Only modify code within MANUAL() sections
# or your changes may be overwritten later!
# !!!

from __future__ import annotations

from typing import Any, Dict

from stytch_management.errors import ClientError
from stytch_management.http_client import HTTPClient
from stytch_management.models.secrets import (
    CreateResponse,
    DeleteResponse,
    GetAllResponse,
    GetResponse,
)


class Secrets:
    """Resource client for Secrets operations."""

    def __init__(self, http_client: HTTPClient) -> None:
        self._http_client = http_client

    def create(
        self,
        project_slug: str,
        environment_slug: str,
    ) -> CreateResponse:
        """Create creates a secret for an environment. The response contains the full secret value, which will not be exposed in future Get requests.

        Fields:
          - project_slug: ProjectSlug is the slug of the project.
          - environment_slug: EnvironmentSlug is the slug of the environment.
        """
        if not project_slug:
            raise ClientError("MISSING_PATH_PARAMETER", "project_slug cannot be empty")
        if not environment_slug:
            raise ClientError(
                "MISSING_PATH_PARAMETER", "environment_slug cannot be empty"
            )
        data: Dict[str, Any] = {}

        # Build URL with path parameters
        path = (
            "/pwa/v3/projects/${project_slug}/environments/${environment_slug}/secrets"
        )
        path = path.replace("${project_slug}", str(project_slug))
        path = path.replace("${environment_slug}", str(environment_slug))

        response_json = self._http_client.post(path, json=data if data else None)

        return CreateResponse(**response_json)

    def get(
        self,
        project_slug: str,
        environment_slug: str,
        secret_id: str,
    ) -> GetResponse:
        """Get retrieves a secret for an environment.

        Fields:
          - project_slug: ProjectSlug is the slug of the project.
          - environment_slug: EnvironmentSlug is the slug of the environment.
          - secret_id: The ID of the secret to retrieve.
        """
        if not project_slug:
            raise ClientError("MISSING_PATH_PARAMETER", "project_slug cannot be empty")
        if not environment_slug:
            raise ClientError(
                "MISSING_PATH_PARAMETER", "environment_slug cannot be empty"
            )
        if not secret_id:
            raise ClientError("MISSING_PATH_PARAMETER", "secret_id cannot be empty")
        data: Dict[str, Any] = {}

        # Build URL with path parameters
        path = "/pwa/v3/projects/${project_slug}/environments/${environment_slug}/secrets/${secret_id}"
        path = path.replace("${project_slug}", str(project_slug))
        path = path.replace("${environment_slug}", str(environment_slug))
        path = path.replace("${secret_id}", str(secret_id))

        params: Dict[str, Any] = {}
        response_json = self._http_client.get(path, params=params if params else None)

        return GetResponse(**response_json)

    def get_all(
        self,
        project_slug: str,
        environment_slug: str,
    ) -> GetAllResponse:
        """GetAll retrieves all secrets for an environment.

        Fields:
          - project_slug: ProjectSlug is the slug of the project.
          - environment_slug: EnvironmentSlug is the slug of the environment.
        """
        if not project_slug:
            raise ClientError("MISSING_PATH_PARAMETER", "project_slug cannot be empty")
        if not environment_slug:
            raise ClientError(
                "MISSING_PATH_PARAMETER", "environment_slug cannot be empty"
            )
        data: Dict[str, Any] = {}

        # Build URL with path parameters
        path = (
            "/pwa/v3/projects/${project_slug}/environments/${environment_slug}/secrets"
        )
        path = path.replace("${project_slug}", str(project_slug))
        path = path.replace("${environment_slug}", str(environment_slug))

        params: Dict[str, Any] = {}
        response_json = self._http_client.get(path, params=params if params else None)

        return GetAllResponse(**response_json)

    def delete(
        self,
        project_slug: str,
        environment_slug: str,
        secret_id: str,
    ) -> DeleteResponse:
        """Delete deletes a secret for an environment.

        Fields:
          - project_slug: ProjectSlug is the slug of the project.
          - environment_slug: EnvironmentSlug is the slug of the environment.
          - secret_id: The ID of the secret to delete.
        """
        if not project_slug:
            raise ClientError("MISSING_PATH_PARAMETER", "project_slug cannot be empty")
        if not environment_slug:
            raise ClientError(
                "MISSING_PATH_PARAMETER", "environment_slug cannot be empty"
            )
        if not secret_id:
            raise ClientError("MISSING_PATH_PARAMETER", "secret_id cannot be empty")
        data: Dict[str, Any] = {}

        # Build URL with path parameters
        path = "/pwa/v3/projects/${project_slug}/environments/${environment_slug}/secrets/${secret_id}"
        path = path.replace("${project_slug}", str(project_slug))
        path = path.replace("${environment_slug}", str(environment_slug))
        path = path.replace("${secret_id}", str(secret_id))

        response_json = self._http_client.delete(path)

        return DeleteResponse(**response_json)
