# !!!
# WARNING: This file is autogenerated
# Only modify code within MANUAL() sections
# or your changes may be overwritten later!
# !!!

from __future__ import annotations

from typing import Any, Dict, Optional

from stytch_management.errors import ClientError
from stytch_management.http_client import HTTPClient
from stytch_management.models.trustedtokenprofiles import (
    CreatePEMFileResponse,
    CreateResponse,
    DeletePEMFileResponse,
    DeleteResponse,
    GetAllResponse,
    GetPEMFileResponse,
    GetResponse,
    UpdateResponse,
)


class TrustedTokenProfiles:
    """Resource client for TrustedTokenProfiles operations."""

    def __init__(self, http_client: HTTPClient) -> None:
        self._http_client = http_client

    def create(
        self,
        project_slug: str,
        environment_slug: str,
        name: str,
        audience: str,
        issuer: str,
        pem_files: List[str],
        can_jit_provision: bool,
        jwks_url: Optional[str] = None,
        attribute_mapping: Optional[Dict[str, Any]] = None,
        public_key_type: Optional[Union[PublicKeyType, str]] = None,
    ) -> CreateResponse:
        """Create creates a trusted token profile for an environment.

        Fields:
          - project_slug: ProjectSlug is the slug of the project.
          - environment_slug: EnvironmentSlug is the slug of the environment.
          - name: Name is a human-readable name. This does not have to be unique.
          - audience: Audience is the audience for the trusted token profile.
          - issuer: Issuer is the issuer for the trusted token profile.
          - pem_files: PEMFiles is a list of PEM files.
          - can_jit_provision: CanJITProvision indicates whether the trusted token profile can be provisioned JIT.
          - jwks_url: JwksURL is the JWKS URL for the trusted token profile.
          - attribute_mapping: AttributeMapping is the attribute mapping for the trusted token profile.
          - public_key_type: PublicKeyType is the type of public key.
        """
        if not project_slug:
            raise ClientError("MISSING_PATH_PARAMETER", "project_slug cannot be empty")
        if not environment_slug:
            raise ClientError(
                "MISSING_PATH_PARAMETER", "environment_slug cannot be empty"
            )
        data: Dict[str, Any] = {}
        data["name"] = name
        data["audience"] = audience
        data["issuer"] = issuer
        data["pem_files"] = pem_files
        data["can_jit_provision"] = can_jit_provision
        if jwks_url is not None:
            data["jwks_url"] = jwks_url
        if attribute_mapping is not None:
            data["attribute_mapping"] = attribute_mapping
        if public_key_type is not None:
            data["public_key_type"] = public_key_type

        # Build URL with path parameters
        path = "/pwa/v3/projects/${project_slug}/environments/${environment_slug}/trusted_token_profiles"
        path = path.replace("${project_slug}", str(project_slug))
        path = path.replace("${environment_slug}", str(environment_slug))

        response_json = self._http_client.post(path, json=data if data else None)

        return CreateResponse(**response_json)

    def get(
        self,
        project_slug: str,
        environment_slug: str,
        profile_id: str,
    ) -> GetResponse:
        """Get retrieves the trusted token profile for an environment.

        Fields:
          - project_slug: ProjectSlug is the slug of the project.
          - environment_slug: EnvironmentSlug is the slug of the environment.
          - profile_id: ProfileID is the unique identifier for the trusted token profile.
        """
        if not project_slug:
            raise ClientError("MISSING_PATH_PARAMETER", "project_slug cannot be empty")
        if not environment_slug:
            raise ClientError(
                "MISSING_PATH_PARAMETER", "environment_slug cannot be empty"
            )
        if not profile_id:
            raise ClientError("MISSING_PATH_PARAMETER", "profile_id cannot be empty")
        data: Dict[str, Any] = {}

        # Build URL with path parameters
        path = "/pwa/v3/projects/${project_slug}/environments/${environment_slug}/trusted_token_profiles/${profile_id}"
        path = path.replace("${project_slug}", str(project_slug))
        path = path.replace("${environment_slug}", str(environment_slug))
        path = path.replace("${profile_id}", str(profile_id))

        params: Dict[str, Any] = {}
        response_json = self._http_client.get(path, params=params if params else None)

        return GetResponse(**response_json)

    def get_all(
        self,
        project_slug: str,
        environment_slug: str,
    ) -> GetAllResponse:
        """GetAll retrieves all the trusted token profiles for an environment.

        Fields:
          - project_slug: ProjectSlug is the slug of the project.
          - environment_slug: EnvironmentSlug is the slug of the environment.
        """
        if not project_slug:
            raise ClientError("MISSING_PATH_PARAMETER", "project_slug cannot be empty")
        if not environment_slug:
            raise ClientError(
                "MISSING_PATH_PARAMETER", "environment_slug cannot be empty"
            )
        data: Dict[str, Any] = {}

        # Build URL with path parameters
        path = "/pwa/v3/projects/${project_slug}/environments/${environment_slug}/trusted_token_profiles"
        path = path.replace("${project_slug}", str(project_slug))
        path = path.replace("${environment_slug}", str(environment_slug))

        params: Dict[str, Any] = {}
        response_json = self._http_client.get(path, params=params if params else None)

        return GetAllResponse(**response_json)

    def update(
        self,
        project_slug: str,
        environment_slug: str,
        profile_id: str,
        name: Optional[str] = None,
        audience: Optional[str] = None,
        issuer: Optional[str] = None,
        jwks_url: Optional[str] = None,
        attribute_mapping: Optional[Dict[str, Any]] = None,
        can_jit_provision: Optional[bool] = None,
    ) -> UpdateResponse:
        """Update updates a trusted token profile for an environment.

        Fields:
          - project_slug: ProjectSlug is the slug of the project.
          - environment_slug: EnvironmentSlug is the slug of the environment.
          - profile_id: ProfileID is the unique identifier for the trusted token profile.
          - name: Name is a human-readable name. This does not have to be unique.
          - audience: Audience is the audience for the trusted token profile.
          - issuer: Issuer is the issuer for the trusted token profile.
          - jwks_url: JwksURL is the JWKS URL for the trusted token profile.
          - attribute_mapping: AttributeMapping is the attribute mapping for the trusted token profile.
          - can_jit_provision: CanJITProvision indicates whether the trusted token profile can be provisioned JIT.
        """
        if not project_slug:
            raise ClientError("MISSING_PATH_PARAMETER", "project_slug cannot be empty")
        if not environment_slug:
            raise ClientError(
                "MISSING_PATH_PARAMETER", "environment_slug cannot be empty"
            )
        if not profile_id:
            raise ClientError("MISSING_PATH_PARAMETER", "profile_id cannot be empty")
        data: Dict[str, Any] = {}
        if name is not None:
            data["name"] = name
        if audience is not None:
            data["audience"] = audience
        if issuer is not None:
            data["issuer"] = issuer
        if jwks_url is not None:
            data["jwks_url"] = jwks_url
        if attribute_mapping is not None:
            data["attribute_mapping"] = attribute_mapping
        if can_jit_provision is not None:
            data["can_jit_provision"] = can_jit_provision

        # Build URL with path parameters
        path = "/pwa/v3/projects/${project_slug}/environments/${environment_slug}/trusted_token_profiles/${profile_id}"
        path = path.replace("${project_slug}", str(project_slug))
        path = path.replace("${environment_slug}", str(environment_slug))
        path = path.replace("${profile_id}", str(profile_id))

        response_json = self._http_client.patch(path, json=data if data else None)

        return UpdateResponse(**response_json)

    def delete(
        self,
        project_slug: str,
        environment_slug: str,
        profile_id: str,
    ) -> DeleteResponse:
        """Delete deletes a trusted token profile for an environment.

        Fields:
          - project_slug: ProjectSlug is the slug of the project.
          - environment_slug: EnvironmentSlug is the slug of the environment.
          - profile_id: ProfileID is the unique identifier for the trusted token profile.
        """
        if not project_slug:
            raise ClientError("MISSING_PATH_PARAMETER", "project_slug cannot be empty")
        if not environment_slug:
            raise ClientError(
                "MISSING_PATH_PARAMETER", "environment_slug cannot be empty"
            )
        if not profile_id:
            raise ClientError("MISSING_PATH_PARAMETER", "profile_id cannot be empty")
        data: Dict[str, Any] = {}

        # Build URL with path parameters
        path = "/pwa/v3/projects/${project_slug}/environments/${environment_slug}/trusted_token_profiles/${profile_id}"
        path = path.replace("${project_slug}", str(project_slug))
        path = path.replace("${environment_slug}", str(environment_slug))
        path = path.replace("${profile_id}", str(profile_id))

        response_json = self._http_client.delete(path)

        return DeleteResponse(**response_json)

    def create_pem_file(
        self,
        project_slug: str,
        environment_slug: str,
        profile_id: str,
        public_key: str,
    ) -> CreatePEMFileResponse:
        """CreatePEM creates a PEM file for a trusted token profile for an environment.

        Fields:
          - project_slug: ProjectSlug is the slug of the project.
          - environment_slug: EnvironmentSlug is the slug of the environment.
          - profile_id: ProfileID is the unique identifier for the trusted token profile.
          - public_key: PublicKey is the public key content.
        """
        if not project_slug:
            raise ClientError("MISSING_PATH_PARAMETER", "project_slug cannot be empty")
        if not environment_slug:
            raise ClientError(
                "MISSING_PATH_PARAMETER", "environment_slug cannot be empty"
            )
        if not profile_id:
            raise ClientError("MISSING_PATH_PARAMETER", "profile_id cannot be empty")
        data: Dict[str, Any] = {}
        data["public_key"] = public_key

        # Build URL with path parameters
        path = "/pwa/v3/projects/${project_slug}/environments/${environment_slug}/trusted_token_profiles/${profile_id}/keys"
        path = path.replace("${project_slug}", str(project_slug))
        path = path.replace("${environment_slug}", str(environment_slug))
        path = path.replace("${profile_id}", str(profile_id))

        response_json = self._http_client.post(path, json=data if data else None)

        return CreatePEMFileResponse(**response_json)

    def delete_pem_file(
        self,
        project_slug: str,
        environment_slug: str,
        profile_id: str,
        pem_file_id: str,
    ) -> DeletePEMFileResponse:
        """DeletePEM deletes a PEM file for a trusted token profile for an environment.

        Fields:
          - project_slug: ProjectSlug is the slug of the project.
          - environment_slug: EnvironmentSlug is the slug of the environment.
          - profile_id: ProfileID is the unique identifier for the trusted token profile.
          - pem_file_id: PEMFileID is the unique identifier for the PEM file.
        """
        if not project_slug:
            raise ClientError("MISSING_PATH_PARAMETER", "project_slug cannot be empty")
        if not environment_slug:
            raise ClientError(
                "MISSING_PATH_PARAMETER", "environment_slug cannot be empty"
            )
        if not profile_id:
            raise ClientError("MISSING_PATH_PARAMETER", "profile_id cannot be empty")
        if not pem_file_id:
            raise ClientError("MISSING_PATH_PARAMETER", "pem_file_id cannot be empty")
        data: Dict[str, Any] = {}

        # Build URL with path parameters
        path = "/pwa/v3/projects/${project_slug}/environments/${environment_slug}/trusted_token_profiles/${profile_id}/keys/${pem_file_id}"
        path = path.replace("${project_slug}", str(project_slug))
        path = path.replace("${environment_slug}", str(environment_slug))
        path = path.replace("${profile_id}", str(profile_id))
        path = path.replace("${pem_file_id}", str(pem_file_id))

        response_json = self._http_client.delete(path)

        return DeletePEMFileResponse(**response_json)

    def get_pem_file(
        self,
        project_slug: str,
        environment_slug: str,
        profile_id: str,
        pem_file_id: str,
    ) -> GetPEMFileResponse:
        """GetPEM retrieves a PEM file for a trusted token profile for an environment.

        Fields:
          - project_slug: ProjectSlug is the slug of the project.
          - environment_slug: EnvironmentSlug is the slug of the environment.
          - profile_id: ProfileID is the unique identifier for the trusted token profile.
          - pem_file_id: PEMFileID is the unique identifier for the PEM file.
        """
        if not project_slug:
            raise ClientError("MISSING_PATH_PARAMETER", "project_slug cannot be empty")
        if not environment_slug:
            raise ClientError(
                "MISSING_PATH_PARAMETER", "environment_slug cannot be empty"
            )
        if not profile_id:
            raise ClientError("MISSING_PATH_PARAMETER", "profile_id cannot be empty")
        if not pem_file_id:
            raise ClientError("MISSING_PATH_PARAMETER", "pem_file_id cannot be empty")
        data: Dict[str, Any] = {}

        # Build URL with path parameters
        path = "/pwa/v3/projects/${project_slug}/environments/${environment_slug}/trusted_token_profiles/${profile_id}/keys/${pem_file_id}"
        path = path.replace("${project_slug}", str(project_slug))
        path = path.replace("${environment_slug}", str(environment_slug))
        path = path.replace("${profile_id}", str(profile_id))
        path = path.replace("${pem_file_id}", str(pem_file_id))

        params: Dict[str, Any] = {}
        response_json = self._http_client.get(path, params=params if params else None)

        return GetPEMFileResponse(**response_json)
